/**
 * Multi-block *document* templates (as opposed to single-block scaffolds) —
 * `avo template <name>` / `avo new --type <name>`.
 *
 * Each template is a complete, `avo check`-clean starting doc for a common doc
 * kind, following the matching playbook in the authoring skill
 * (`.avodado/skill/SKILL.md`, *Document playbooks*). Placeholder content is a
 * small believable example the author edits — never "TODO".
 */

const ADR_TEMPLATE = [
  '```meta',
  'title: ADR-NNN — decision title',
  'subtitle: One line on what we decided and why it matters.',
  'tag: ADR · Proposed · YYYY-MM-DD',
  '```',
  '',
  '## Status',
  '',
  '**Proposed** — YYYY-MM-DD. (Proposed → Accepted → Superseded.)',
  '',
  '## Context',
  '',
  'What forces a decision here? The constraints, requirements, and the problem',
  'being solved. Two to four sentences of plain prose — no block needed.',
  '',
  '```callout',
  'tone: note',
  'title: Decision',
  'body: "State the decision in one or two sentences — what we will do, and the single most important reason why."',
  '```',
  '',
  '## Options considered',
  '',
  '```proscons',
  'id: the-choice',
  'title: Chosen option vs the alternative',
  'prosLabel: Chosen option',
  'consLabel: The alternative',
  'pros:',
  '  - A concrete reason the chosen option wins',
  '  - Another benefit worth the trade-off',
  'cons:',
  '  - A real cost of the alternative',
  '  - Another drawback we are accepting against',
  '```',
  '',
  '## Architecture',
  '',
  '```block',
  'id: architecture',
  'title: How it fits together',
  'nodes:',
  '  - { id: client, col: 1, row: 1, kind: client, name: Client }',
  '  - { id: svc, col: 2, row: 1, kind: service, name: Service, tech: your stack }',
  '  - { id: db, col: 3, row: 1, kind: store, name: Database }',
  'edges:',
  '  - { from: client, to: svc }',
  '  - { from: svc, to: db }',
  '```',
  '',
  '## Consequences',
  '',
  '```tracker',
  'id: consequences',
  'title: Consequences & follow-ups',
  'items:',
  '  - { task: "Something that becomes easier or newly required", status: todo, priority: high }',
  '  - { task: "A migration or new responsibility this creates", status: todo, priority: med }',
  '  - { task: "A risk to watch as we roll this out", status: todo, priority: low }',
  '```',
  '',
].join('\n');

const DESIGN_DOC_TEMPLATE = [
  '```meta',
  'title: Media processing off the upload path',
  'subtitle: A proposal to move thumbnailing and transcoding to an async pipeline.',
  'tag: RFC · Draft',
  '```',
  '',
  '## Problem',
  '',
  'Uploads block on media processing today: a 40 MB video holds an API worker',
  'for up to 90 seconds, and one slow transcode can starve the pool. Describe',
  'the pain in two to four sentences of plain prose — numbers beat adjectives.',
  '',
  '## Where the time goes',
  '',
  '```mece',
  'id: rfc-problem-breakdown',
  'title: Why uploads are slow',
  'nodes:',
  '  - { id: root, label: Slow uploads }',
  '  - { id: cpu, parent: root, label: CPU-bound work }',
  '  - { id: io, parent: root, label: I/O-bound work }',
  '  - { id: c1, parent: cpu, label: Transcoding, note: "70% of wall time" }',
  '  - { id: c2, parent: cpu, label: Thumbnailing }',
  '  - { id: i1, parent: io, label: Object-store writes }',
  '```',
  '',
  '## Alternatives',
  '',
  '```options',
  'id: rfc-alternatives',
  'title: Approaches explored',
  'items:',
  '  - { kicker: Option 1, title: Bigger workers, how: Scale the API pool vertically., pros: [No code change], cons: [Cost scales with the worst upload, Still blocks the pool], verdict: "REJECTED — buys months, not a fix", tone: rejected }',
  '  - { kicker: Option 2, title: Async pipeline, how: "Accept the upload, enqueue processing, notify on completion.", pros: [Upload latency independent of media size, Retryable steps], cons: [Eventual consistency for previews], verdict: "CHOSEN — isolates the slow work", tone: chosen }',
  '```',
  '',
  '## Proposed design',
  '',
  '```block',
  'id: rfc-proposed-design',
  'title: The async pipeline',
  'nodes:',
  '  - { id: api, col: 1, row: 1, kind: service, name: Upload API, tech: Node }',
  '  - { id: q, col: 2, row: 1, kind: queue, name: media.jobs, tech: SQS }',
  '  - { id: worker, col: 3, row: 1, kind: service, name: Media worker, tech: ffmpeg }',
  '  - { id: s3, col: 2, row: 2, kind: store, name: Object store, tech: S3 }',
  'edges:',
  '  - { from: api, to: s3, label: raw upload }',
  '  - { from: api, to: q, label: enqueue }',
  '  - { from: q, to: worker, kind: dashed }',
  '  - { from: worker, to: s3, label: renditions }',
  '```',
  '',
  '## Behavior',
  '',
  '```sequence',
  'id: rfc-seq-upload',
  'title: One upload, end to end',
  'actors:',
  '  - { id: Client, name: Client }',
  '  - { id: API, name: Upload API }',
  '  - { id: Worker, name: Media worker }',
  'messages:',
  '  - { from: Client, to: API, label: POST /uploads, kind: sync }',
  '  - { from: API, to: Client, label: "202 Accepted + upload id", kind: response }',
  '  - { from: API, to: Worker, label: media.jobs message, kind: async }',
  '  - { from: Worker, to: Client, label: webhook media.ready, kind: async }',
  '```',
  '',
  '## Open questions',
  '',
  '```tracker',
  'id: rfc-open-questions',
  'title: To resolve before build',
  'items:',
  '  - { task: "Poison-pill handling — max retries before dead-letter?", status: todo, priority: high }',
  '  - { task: "Do previews need a placeholder rendition synchronously?", status: todo, priority: med }',
  '```',
  '',
].join('\n');

const RUNBOOK_TEMPLATE = [
  '```meta',
  'title: Runbook — elevated 5xx on the API',
  'subtitle: Triage and mitigate a 5xx spike on the public API.',
  'tag: Runbook · On-call',
  '```',
  '',
  '```callout',
  'tone: warn',
  'title: When to use this',
  'body: "The api-5xx-rate alert fired (>1% of requests over 5 minutes). If the whole site is down, use the total-outage runbook instead."',
  '```',
  '',
  '## Triage',
  '',
  '```flow',
  'id: rb-triage',
  'title: Decide which case you are in',
  'nodes:',
  '  - { id: start, col: 1, row: 1, kind: start, label: Alert fires }',
  '  - { id: deploy, col: 2, row: 1, kind: decision, label: "Deploy in last 30m?" }',
  '  - { id: rollback, col: 3, row: 1, kind: process, label: Roll back }',
  '  - { id: db, col: 2, row: 2, kind: decision, label: "DB latency high?" }',
  '  - { id: failover, col: 3, row: 2, kind: process, label: Fail over replica }',
  '  - { id: escalate, col: 2, row: 3, kind: end, label: Escalate to platform }',
  'edges:',
  '  - { from: start, to: deploy }',
  '  - { from: deploy, to: rollback, label: "yes" }',
  '  - { from: deploy, to: db, label: "no" }',
  '  - { from: db, to: failover, label: "yes" }',
  '  - { from: db, to: escalate, label: "no", kind: error }',
  '```',
  '',
  '## Act',
  '',
  '```steps',
  'id: rb-mitigation',
  'title: Roll back the last deploy',
  'items:',
  '  - title: Confirm the suspect release',
  '    body: The release that started serving right before the spike.',
  '    code: kubectl rollout history deploy/api | tail -3',
  '    lang: bash',
  '  - title: Roll back',
  '    code: kubectl rollout undo deploy/api',
  '    lang: bash',
  '    note: Rollback takes ~3 minutes to settle; watch the error rate, not the pods.',
  '  - title: Verify',
  '    body: 5xx rate should drop below 0.1% within five minutes.',
  '    code: curl -s https://status.internal/api/error-rate',
  '    lang: bash',
  '```',
  '',
  '## Symptom → action',
  '',
  '```table',
  'id: rb-symptom-action',
  'columns: [Symptom, Likely cause, Action]',
  'rows:',
  '  - ["5xx only on POST /orders", "Payment provider degraded", "Enable the capture circuit breaker"]',
  '  - ["Timeouts across all routes", "DB primary saturated", "Fail over to the replica"]',
  '  - ["Spike right after a deploy", "Bad release", "Roll back (steps above)"]',
  '```',
  '',
].join('\n');

const ROADMAP_TEMPLATE = [
  '```meta',
  'title: Payments platform — H2 roadmap',
  'subtitle: What ships when, and the targets each phase moves.',
  'tag: Roadmap · H2',
  '```',
  '',
  '## Targets',
  '',
  '```stats',
  'id: rm-targets',
  'title: Where H2 should land',
  'stats:',
  '  - { value: "99.95%", label: Checkout availability, delta: "+0.15pp", trend: up }',
  '  - { value: "600ms", label: Checkout p95, delta: "-1.8s", trend: up }',
  '  - { value: "3", label: New payment methods, trend: flat }',
  '```',
  '',
  '## Phases',
  '',
  '```timeline',
  'id: rm-phases',
  'items:',
  '  - { label: Async capture, date: Jul, status: done, desc: Capture moves off the request path. }',
  '  - { label: Wallets, date: Aug-Sep, status: current, desc: Apple Pay + Google Pay behind a flag. }',
  '  - { label: Bank transfers, date: Oct, status: next, desc: SEPA + ACH via the PSP. }',
  '  - { label: Chargeback automation, date: Nov-Dec, status: future, desc: Evidence packets built from order data. }',
  '```',
  '',
  '## Now / next / later',
  '',
  '```kanban',
  'id: rm-board',
  'columns:',
  '  - label: Now',
  '    cards:',
  '      - { title: Wallet tokenization, tag: wallets }',
  '      - { title: Capture worker autoscaling }',
  '  - label: Next',
  '    cards:',
  '      - { title: SEPA mandate flow, tag: transfers }',
  '  - label: Later',
  '    cards:',
  '      - { title: Chargeback evidence builder }',
  '```',
  '',
  '## Workstreams',
  '',
  '```tracker',
  'id: rm-workstreams',
  'items:',
  '  - { task: Wallets GA behind a flag, status: doing, priority: high, owner: Payments, due: Sep 15 }',
  '  - { task: PSP contract for bank transfers, status: todo, priority: high, owner: Finance, due: Aug 30 }',
  '  - { task: Deprecate the legacy capture job, status: todo, priority: med, owner: Payments }',
  '```',
  '',
].join('\n');

const API_SPEC_TEMPLATE = [
  '```meta',
  'title: Sessions API',
  'subtitle: Create and inspect login sessions for first-party clients.',
  'tag: API · v1',
  '```',
  '',
  'All routes are under `https://api.example.com/v1` and require a client key.',
  '',
  '## Create a session',
  '',
  '```endpoint',
  'id: post-sessions',
  'method: POST',
  'path: /sessions',
  'title: Create a session',
  'description: Exchange user credentials for a session token.',
  'auth: Client key (X-Client-Key header)',
  'body:',
  '  - { name: email, type: string, required: true, desc: Account email }',
  '  - { name: password, type: string, required: true, desc: Account password }',
  '  - { name: remember, type: boolean, desc: Extend the session to 30 days }',
  'responses:',
  '  - { status: 201, desc: Session created }',
  '  - { status: 401, desc: Bad credentials }',
  '  - { status: 429, desc: Too many attempts — retry after the indicated delay }',
  'request: |',
  '  { "email": "sam@example.com", "password": "…", "remember": true }',
  'response: |',
  '  { "token": "ses_9f2…", "expiresAt": "2026-08-01T12:00:00Z" }',
  '```',
  '',
  '## Request flow',
  '',
  '```sequence',
  'id: sessions-seq-create',
  'title: Credential exchange',
  'endpoint: { method: POST, path: /sessions }',
  'actors:',
  '  - { id: Client, name: Client }',
  '  - { id: API, name: Sessions API }',
  '  - { id: IDP, name: Identity store }',
  'messages:',
  '  - { from: Client, to: API, label: POST /sessions, kind: sync }',
  '  - { from: API, to: IDP, label: verify credentials, kind: sync }',
  '  - { from: IDP, to: API, label: user record, kind: response }',
  '  - { from: API, to: Client, label: "201 + session token", kind: response }',
  '```',
  '',
  '## Data touched',
  '',
  '```erd',
  'id: sessions-model',
  'entities:',
  '  - name: users',
  '    columns:',
  '      - { name: id, type: uuid, pk: true }',
  '      - { name: email, type: text }',
  '  - name: sessions',
  '    columns:',
  '      - { name: id, type: uuid, pk: true }',
  '      - { name: user_id, type: uuid, fk: true }',
  '      - { name: expires_at, type: timestamptz }',
  'relations:',
  '  - { from: users, to: sessions, label: has, card: "1:N" }',
  '```',
  '',
  '## Status codes',
  '',
  '```table',
  'id: sessions-status-codes',
  'columns: [Status, Meaning, Client action]',
  'rows:',
  '  - [201, Session created, Store the token]',
  '  - [401, Bad credentials, Prompt the user again]',
  '  - [429, Rate limited, "Retry after the Retry-After header"]',
  '```',
  '',
].join('\n');

const SYSTEM_DESIGN_TEMPLATE = [
  '```meta',
  'title: Webhook delivery service',
  'subtitle: Design for delivering customer webhooks reliably at platform scale.',
  'tag: System design · Draft',
  '```',
  '',
  '## Requirements',
  '',
  '```drivers',
  'id: wh-requirements',
  'title: What the design must satisfy',
  'items:',
  '  - { title: At-least-once delivery, body: Every event reaches every subscribed endpoint., tag: "MUST", icon: check, accent: green }',
  '  - { title: Ordered per subscription, body: Events for one subscription arrive in order., tag: "MUST", icon: layers, accent: blue }',
  '  - { title: Slow consumers isolated, body: One dead endpoint never delays the rest., tag: "MUST", icon: shield, accent: purple }',
  '  - { title: Replay window, body: Customers can replay the last 7 days., tag: "SHOULD", icon: clock, accent: amber }',
  '```',
  '',
  '## Envelope math',
  '',
  '```envelope',
  'id: wh-envelope',
  'title: Delivery-path capacity',
  'assumptions:',
  '  - { label: Events per day, value: 40M }',
  '  - { label: Subscriptions per event, value: "1.5 avg" }',
  'steps:',
  '  - { label: Deliveries per day, calc: "40M × 1.5", result: 60M/day }',
  '  - { label: Steady QPS, calc: "60M / 86,400 s", result: "≈ 700 rps" }',
  '  - { label: Peak QPS, calc: "700 × 4 (bursts)", result: "≈ 2,800 rps" }',
  'result: { label: Provision for, value: "~5,600 rps (2× peak headroom)" }',
  '```',
  '',
  '## Contract',
  '',
  '```endpoint',
  'id: post-subscriptions',
  'method: POST',
  'path: /webhook-subscriptions',
  'title: Subscribe to events',
  'body:',
  '  - { name: url, type: string, required: true, desc: HTTPS endpoint to deliver to }',
  '  - { name: events, type: "string[]", required: true, desc: Event types to receive }',
  'responses:',
  '  - { status: 201, desc: Subscription created }',
  '  - { status: 422, desc: URL failed the handshake ping }',
  '```',
  '',
  '## High level',
  '',
  '```infra',
  'id: wh-topology',
  'title: Delivery topology',
  'systemLabel: webhooks · production',
  'layers:',
  '  - { label: Ingest }',
  '  - { label: Queueing }',
  '  - { label: Delivery }',
  'nodes:',
  '  - { id: api, layer: 0, kind: service, name: Events API, tech: Go }',
  '  - { id: log, layer: 1, kind: queue, name: event log, tech: Kafka }',
  '  - { id: sched, layer: 2, kind: service, name: Scheduler, tech: per-subscription queues }',
  '  - { id: sender, layer: 2, kind: service, name: Senders, tech: HTTP workers }',
  '  - { id: store, layer: 1, kind: store, name: delivery state, tech: Postgres }',
  'edges:',
  '  - { from: api, to: log }',
  '  - { from: log, to: sched }',
  '  - { from: sched, to: sender }',
  '  - { from: sender, to: store, kind: dashed, label: attempts }',
  '```',
  '',
  '## The bottleneck — slow consumers',
  '',
  '```options',
  'id: wh-isolation-options',
  'title: Isolating slow endpoints',
  'items:',
  '  - { kicker: Option 1, title: Shared worker pool, how: All deliveries through one pool with timeouts., pros: [Simple], cons: [One stuck endpoint consumes the pool], verdict: "REJECTED — fails isolation", tone: rejected }',
  '  - { kicker: Option 2, title: Per-subscription queues, how: Scheduler drains each subscription independently with backoff., pros: [Head-of-line blocking scoped to one customer, Natural per-endpoint rate limits], cons: [More queue state to manage], verdict: "CHOSEN", tone: chosen }',
  '```',
  '',
  '## Objectives',
  '',
  '```slo',
  'id: wh-slos',
  'title: Delivery objectives',
  'items:',
  '  - { name: Delivery latency, sli: Deliveries attempted under 60 s of event time, target: "99%", current: "99.4%", window: 30d, budget: 0.4 }',
  '  - { name: Delivery success, sli: Deliveries succeeding within the retry policy, target: "99.9%", window: 30d, budget: 0.2 }',
  '```',
  '',
  '## Plan',
  '',
  '```timeline',
  'id: wh-plan',
  'items:',
  '  - { label: Ingest + log, date: Q3, status: current, desc: Events API writing to the log. }',
  '  - { label: Scheduler + senders, date: Q3, status: next, desc: Per-subscription delivery with backoff. }',
  '  - { label: Replay API, date: Q4, status: future, desc: 7-day replay from the log. }',
  '```',
  '',
].join('\n');

const AGENT_SYSTEM_TEMPLATE = [
  '```meta',
  'title: Support triage agent',
  'subtitle: How the ticket-triage agent works — loop, prompts, budget, and evals.',
  'tag: Agent system · v1',
  '```',
  '',
  '## Requirements',
  '',
  '```drivers',
  'id: agent-requirements',
  'title: What the agent must do',
  'items:',
  '  - { title: Resolve or route, body: Answer from the KB or escalate to the right queue., tag: "JOB", icon: check, accent: green }',
  '  - { title: Grounded answers, body: Every claim cites a KB article., tag: "GUARDRAIL", icon: shield, accent: purple }',
  '  - { title: Bounded cost, body: "One episode stays under 40k tokens.", tag: "BUDGET", icon: bolt, accent: amber }',
  '```',
  '',
  '## The loop',
  '',
  '```agentloop',
  'id: agent-loop',
  'title: Triage loop',
  'agent:',
  '  name: Triage agent',
  '  model: claude-sonnet-4-6',
  '  note: Routes each ticket to a fix or a human.',
  'env: Customer',
  'tools:',
  '  - { name: search_kb, desc: Search help-center articles }',
  '  - { name: get_account, desc: Look up plan and billing state }',
  '  - { name: create_ticket, desc: Escalate to a human queue }',
  'memory:',
  '  - conversation history',
  '  - customer profile',
  'stop: reply sent or ticket escalated',
  '```',
  '',
  '## Prompt anatomy',
  '',
  '```prompt',
  'id: agent-prompt',
  'title: Triage prompt',
  'segments:',
  '  - kind: system',
  '    label: role + guardrails',
  '    text: "You are a support agent for {{product}}. Answer only from KB articles; cite the article id."',
  '  - kind: user',
  '    text: "Customer ({{plan}} plan) writes: {{ticket}}"',
  'vars:',
  '  - { name: product, desc: Product name from config }',
  '  - { name: plan, desc: Plan tier of the customer }',
  '  - { name: ticket, desc: The inbound ticket body }',
  '```',
  '',
  '## Context budget',
  '',
  '```context',
  'id: agent-budget',
  'title: Where one episode\'s window goes',
  'window: 200000',
  'segments:',
  '  - { label: system prompt, tokens: 4000, accent: navy }',
  '  - { label: tool schemas, tokens: 6000, accent: teal }',
  '  - { label: KB retrieval, tokens: 18000, accent: amber }',
  '  - { label: history, tokens: 12000, accent: purple }',
  '```',
  '',
  '## One turn, end to end',
  '',
  '```sequence',
  'id: agent-seq-turn',
  'title: A tool-using turn',
  'actors:',
  '  - { id: User, name: Customer }',
  '  - { id: Agent, name: Agent }',
  '  - { id: KB, name: search_kb }',
  'messages:',
  '  - { from: User, to: Agent, label: ticket text, kind: sync }',
  '  - { from: Agent, to: KB, label: "search_kb(query)", kind: sync }',
  '  - { from: KB, to: Agent, label: top 3 articles, kind: response }',
  '  - { from: Agent, to: User, label: cited reply, kind: response }',
  '```',
  '',
  '## A real episode',
  '',
  '```trace',
  'id: agent-episode',
  'title: Password reset — one episode',
  'turns:',
  '  - role: user',
  '    text: I never get the reset email.',
  '  - role: assistant',
  '    thinking: Could be a bounce — check delivery before blaming spam.',
  '    text: Let me check our email logs.',
  '  - role: tool',
  '    tool: search_kb',
  '    args: \'{ "query": "reset email not delivered" }\'',
  '    result: "KB-142: bounced mail troubleshooting"',
  '  - role: assistant',
  '    text: "Your mailbox rejected the email (KB-142) — free up space and I will resend it."',
  '```',
  '',
  '## Eval results',
  '',
  '```table',
  'id: agent-evals',
  'columns: [Eval, Target, Current]',
  'rows:',
  '  - [Resolution without escalation, "40%", "46%"]',
  '  - [Citation accuracy, "99%", "98.7%"]',
  '  - ["Tokens per episode (p95)", "40k", "31k"]',
  '```',
  '',
].join('\n');

const DESIGN_SYSTEM_TEMPLATE = [
  '```meta',
  'title: Aurora design system',
  'subtitle: Tokens, type, usage rules, and component status for product teams.',
  'tag: Design system · v2',
  '```',
  '',
  '## Color tokens',
  '',
  '```palette',
  'id: ds-tokens',
  'title: Core palette',
  'cols: 4',
  'colors:',
  '  - { name: Primary, value: "#0E54A1", usage: Buttons and links }',
  '  - { name: Ink, value: "#1F2937", usage: Body text }',
  '  - { name: Surface, value: "#F6F8FB", usage: Card backgrounds }',
  '  - { name: Positive, value: "#1F9747", usage: Success states }',
  '```',
  '',
  '## Type scale',
  '',
  '```typescale',
  'id: ds-type',
  'title: Type scale',
  'items:',
  '  - { name: Display, size: 40, weight: 700, font: display }',
  '  - { name: Heading, size: 24, weight: 700, font: display }',
  '  - { name: Body, size: 15, lineHeight: 1.6 }',
  '  - { name: Caption, size: 12, weight: 500, note: secondary text }',
  '```',
  '',
  '## Usage guidelines',
  '',
  '```dodont',
  'id: ds-button-usage',
  'title: Button usage',
  'dos:',
  '  - { text: Use one primary button per view }',
  '  - { text: Write labels as verbs, example: "Save changes" }',
  'donts:',
  '  - { text: Stack two primary buttons side by side }',
  '  - { text: Disable a button without explaining why, example: "tooltip: Add a line item first" }',
  '```',
  '',
  '## Component status',
  '',
  '```inventory',
  'id: ds-components',
  'title: Component inventory',
  'items:',
  '  - { name: Button, status: stable, tag: v2 }',
  '  - { name: Data table, status: beta, note: API may change before GA }',
  '  - { name: Date picker, status: experimental }',
  '  - { name: Modal (legacy), status: deprecated, note: Use Dialog instead }',
  '```',
  '',
  '## Key screen',
  '',
  '```wireframe',
  'id: ds-key-screen',
  'title: The settings pattern',
  'screens:',
  '  - device: browser',
  '    title: Settings',
  '    url: app.example.com/settings',
  '    elements:',
  '      - { type: nav, label: "Profile, Billing, Team" }',
  '      - { type: header, label: Billing }',
  '      - { type: list, rows: 3 }',
  '      - { type: button, label: Update plan }',
  '```',
  '',
].join('\n');

const POSTMORTEM_TEMPLATE = [
  '```meta',
  'title: Postmortem — checkout outage 2026-06-12',
  'subtitle: 41 minutes of failed checkouts caused by an expired PSP certificate.',
  'tag: Postmortem · SEV-1 · Resolved',
  '```',
  '',
  '```callout',
  'id: pm-impact',
  'tone: danger',
  'title: Impact',
  'body: "41 minutes of checkout failures (14:03-14:44 UTC). ~3,100 failed purchases, ~$46k delayed revenue. No data loss; retried payments settled by 16:00."',
  '```',
  '',
  '## Timeline',
  '',
  '```timeline',
  'id: pm-timeline',
  'items:',
  '  - { label: Cert expires, date: "14:03", status: done, desc: PSP client certificate lapses; captures start failing. }',
  '  - { label: Alert fires, date: "14:07", status: done, desc: checkout-error-rate pages the on-call. }',
  '  - { label: Root cause found, date: "14:31", status: done, desc: TLS handshake errors traced to the expired cert. }',
  '  - { label: Mitigated, date: "14:44", status: done, desc: Renewed cert deployed; error rate back to baseline. }',
  '```',
  '',
  '## Root cause',
  '',
  '```mece',
  'id: pm-root-cause',
  'title: Why checkouts failed',
  'nodes:',
  '  - { id: root, label: Checkout failures }',
  '  - { id: trigger, parent: root, label: Trigger }',
  '  - { id: defense, parent: root, label: Missing defenses }',
  '  - { id: t1, parent: trigger, label: PSP cert expired, note: issued 2025-06-12 }',
  '  - { id: d1, parent: defense, label: No expiry monitoring }',
  '  - { id: d2, parent: defense, label: No capture fallback path }',
  '```',
  '',
  '## Action items',
  '',
  '```tracker',
  'id: pm-actions',
  'title: Corrective actions',
  'items:',
  '  - { task: Alert on certs expiring within 21 days, status: doing, priority: high, owner: Platform, due: Jun 26 }',
  '  - { task: Automate PSP cert rotation, status: todo, priority: high, owner: Payments, due: Jul 15 }',
  '  - { task: Queue captures when the PSP is unreachable, status: todo, priority: med, owner: Payments }',
  '```',
  '',
].join('\n');

const DATA_MODEL_TEMPLATE = [
  '```meta',
  'title: Orders data model',
  'subtitle: The tables behind ordering, and the lifecycle of an order row.',
  'tag: Data model · v1',
  '```',
  '',
  '## Entities',
  '',
  '```erd',
  'id: orders-erd',
  'title: Orders and their line items',
  'entities:',
  '  - name: users',
  '    columns:',
  '      - { name: id, type: uuid, pk: true }',
  '      - { name: email, type: text }',
  '  - name: orders',
  '    columns:',
  '      - { name: id, type: uuid, pk: true }',
  '      - { name: user_id, type: uuid, fk: true }',
  '      - { name: status, type: order_status }',
  '      - { name: total_cents, type: bigint }',
  '  - name: order_items',
  '    columns:',
  '      - { name: id, type: uuid, pk: true }',
  '      - { name: order_id, type: uuid, fk: true }',
  '      - { name: sku, type: text }',
  '      - { name: qty, type: int }',
  'relations:',
  '  - { from: users, to: orders, label: places, card: "1:N" }',
  '  - { from: orders, to: order_items, label: contains, card: "1:N" }',
  '```',
  '',
  '## Field semantics',
  '',
  '```table',
  'id: orders-field-semantics',
  'columns: [Field, Semantics]',
  'rows:',
  '  - [orders.status, "Enum order_status — see the lifecycle below; only the state machine writes it"]',
  '  - [orders.total_cents, "Integer cents, never floats; recomputed from items on every mutation"]',
  '  - [order_items.sku, "Denormalized from the catalog at purchase time — price changes never rewrite history"]',
  '```',
  '',
  '## Record lifecycle',
  '',
  '```state',
  'id: order-lifecycle',
  'title: order_status transitions',
  'states:',
  '  - { id: s0, col: 1, row: 1, kind: start }',
  '  - { id: pending, col: 2, row: 1, kind: wait, name: PENDING }',
  '  - { id: paid, col: 3, row: 1, kind: active, name: PAID }',
  '  - { id: shipped, col: 4, row: 1, kind: active, name: SHIPPED }',
  '  - { id: done, col: 5, row: 1, kind: terminal }',
  '  - { id: cancelled, col: 3, row: 2, kind: terminal, name: CANCELLED }',
  'transitions:',
  '  - { from: s0, to: pending, event: create }',
  '  - { from: pending, to: paid, event: capture }',
  '  - { from: pending, to: cancelled, event: "cancel / timeout" }',
  '  - { from: paid, to: shipped, event: fulfil }',
  '  - { from: shipped, to: done, event: deliver }',
  '```',
  '',
].join('\n');

const DECK_TEMPLATE = [
  '```meta',
  'title: Fixing checkout latency',
  'subtitle: What we changed, what it bought us, and what we do next.',
  'tag: Deck · Eng review',
  '```',
  '',
  '## Part 1 — the problem',
  '',
  '```divider',
  'kicker: PART 1',
  'title: Checkout was bleeding conversions',
  'accent: navy',
  '```',
  '',
  '## The synchronous capture call dominated checkout time {split}',
  '',
  'Every 100ms of checkout latency costs ~0.6% conversion. Our p95 had',
  'drifted to 2.4s — and one call was 71% of it.',
  '',
  '```chart',
  'id: deck-latency-breakdown',
  'kind: bar',
  'title: Where the 2.4s went',
  'unit: ms',
  'labels: [Gateway, Fraud, Capture, Persist, Render]',
  'series:',
  '  - { label: p95 ms, accent: navy, values: [120, 260, 1700, 180, 140] }',
  '```',
  '',
  '## Part 2 — the fix',
  '',
  '```divider',
  'kicker: PART 2',
  'title: Move capture off the request path',
  'accent: teal',
  '```',
  '',
  '## One number tells the story {split}',
  '',
  'The async capture change removed the 1.7s synchronous call from the',
  'request path. Nothing else shipped in the window.',
  '',
  '```bignumber',
  'id: deck-money-slide',
  'value: "-75%"',
  'label: Checkout p95 after the change',
  'context: "2.4s → 600ms over four weeks of production traffic"',
  'trend: down',
  'accent: green',
  '```',
  '',
  '## What we do next {split}',
  '',
  'The same pattern applies to every synchronous third-party call on the',
  'hot path — fraud scoring is the next candidate.',
  '',
  '```timeline',
  'id: deck-next-steps',
  'items:',
  '  - { label: Async capture, date: shipped, status: done }',
  '  - { label: Fraud scoring async, date: Q3, status: current }',
  '  - { label: Hot-path audit, date: Q4, status: next }',
  '```',
  '',
  '## What to remember',
  '',
  '```takeaways',
  'id: deck-closing',
  'items:',
  '  - text: The synchronous capture call was the bottleneck',
  '    detail: It accounted for 71% of the 2.4s checkout p95.',
  '  - text: Moving it to a queue cut p95 by 75%',
  '  - text: Conversion recovered within two weeks',
  '  - text: Audit every synchronous third-party call on the hot path',
  '```',
  '',
].join('\n');

/** Full-document templates, keyed by name (`avo template <name>`). */
export const DOC_TEMPLATES: Record<string, string> = {
  adr: ADR_TEMPLATE,
  'design-doc': DESIGN_DOC_TEMPLATE,
  runbook: RUNBOOK_TEMPLATE,
  roadmap: ROADMAP_TEMPLATE,
  'api-spec': API_SPEC_TEMPLATE,
  'system-design': SYSTEM_DESIGN_TEMPLATE,
  'agent-system': AGENT_SYSTEM_TEMPLATE,
  'design-system': DESIGN_SYSTEM_TEMPLATE,
  postmortem: POSTMORTEM_TEMPLATE,
  'data-model': DATA_MODEL_TEMPLATE,
  deck: DECK_TEMPLATE,
};

/** True when `name` is a full-document template rather than a block type. */
export function isDocTemplate(name: string): boolean {
  return Object.prototype.hasOwnProperty.call(DOC_TEMPLATES, name);
}
