/**
 * Multi-block *document* templates (as opposed to single-block scaffolds) —
 * `avo template <name>` / `avo new --type <name>` / studio's "+ New doc"
 * template picker. Pure data, relocated here from the CLI so every consumer
 * (CLI, studio, MCP) shares one source; the CLI re-exports it.
 *
 * Each template is a complete, `avo check`-clean starting doc for a common doc
 * kind, following the matching playbook in the authoring skill
 * (`.avodado/skill/SKILL.md`, *Document playbooks*). Placeholder content is a
 * small believable example the author edits — never "TODO".
 */

const ADR_TEMPLATE = [
  '```meta',
  'title: ADR-014 — Idempotency keys on the payments API',
  'subtitle: Clients supply a key; the API replays the first response instead of charging twice.',
  'tag: ADR · Accepted · 2026-03-04',
  '```',
  '',
  '## Status',
  '',
  '**Accepted** — 2026-03-04. Supersedes ADR-009 (retry budgets). Proposed → Accepted → Superseded.',
  '',
  '## Context',
  '',
  'Mobile clients retry `POST /payments` whenever the network drops, and a retry',
  'that lands after the charge succeeded bills the customer a second time. We saw',
  'nine duplicate charges last quarter, every one of them refunded by hand. The',
  'PSP deduplicates on its own reference, but only within a five-minute window,',
  'which is shorter than our longest client retry backoff.',
  '',
  '```callout',
  'tone: note',
  'title: Decision',
  'body: "Clients send an `Idempotency-Key` header on every mutating payments call. The API stores the key with the response for 24 hours and replays that response verbatim for any repeat, so a retry can never produce a second charge."',
  '```',
  '',
  '## What forced it',
  '',
  '```drivers',
  'id: forces',
  'title: The forces behind this decision',
  'items:',
  '  - { title: Retries are not optional, body: "Mobile networks drop mid-request, and the client cannot tell a lost response from a failed charge.", tag: Constraint, icon: bolt, accent: amber }',
  '  - { title: The PSP window is too short, body: "Provider-side dedup lasts five minutes; our longest client backoff is thirty.", tag: Constraint, icon: clock, accent: red }',
  '  - { title: Money is not idempotent by nature, body: "Every duplicate is a refund, a support ticket and a trust cost we cannot automate away.", tag: Risk, icon: shield, accent: navy }',
  '  - { title: The ecosystem already agreed, body: "Stripe and Adyen both use a client-supplied key header — our SDK users expect it.", tag: Precedent, icon: check, accent: teal }',
  '```',
  '',
  '## How it works',
  '',
  '```sequence',
  'id: replay',
  'title: The second call never reaches the PSP',
  'endpoint: { method: POST, path: /payments }',
  'actors:',
  '  - { id: client, name: Mobile client }',
  '  - { id: api, name: Payments API }',
  '  - { id: keys, name: Key store, sub: "Redis, 24h TTL" }',
  '  - { id: psp, name: PSP, external: true }',
  'messages:',
  '  - { from: client, to: api, label: "POST /payments (key: 9f2c…)", kind: sync }',
  '  - { from: api, to: keys, label: claim 9f2c…, kind: sync, note: SETNX — the claim is the lock. }',
  '  - { from: api, to: psp, label: charge, kind: sync }',
  '  - { from: api, to: keys, label: store response, kind: sync }',
  '  - { from: api, to: client, label: 201 Created, kind: response }',
  '  - { from: client, to: api, label: "retry, same key", kind: sync, note: The network dropped the first response. }',
  '  - { from: api, to: keys, label: claim 9f2c… — taken, kind: sync }',
  '  - { from: api, to: client, label: "201 Created (replayed)", kind: response }',
  'foot:',
  '  - { label: Charges, value: exactly one }',
  '  - { label: Replay cost, value: one Redis GET }',
  '```',
  '',
  '## Options considered',
  '',
  '```options',
  'id: the-choice',
  'title: Three ways to make a retry safe',
  'items:',
  '  - title: Client-supplied idempotency key',
  '    kicker: Chosen',
  '    how: The client sends `Idempotency-Key` per user action; the API claims it before charging and replays the stored response for repeats.',
  '    pros:',
  '      - The client defines what "the same request" means, so a deliberate second charge still works',
  '      - One header, one lookup — the replay path is trivial to reason about and to test',
  '      - Matches Stripe and Adyen, so SDK users need no explanation',
  '    cons:',
  '      - Clients must generate and persist a key across retries',
  '      - Adds Redis to the payments write path',
  '    verdict: Cheapest correct answer, and the one our clients already know.',
  '    tone: chosen',
  '  - title: Server-side request fingerprinting',
  '    kicker: Rejected',
  '    how: Hash method, path, body and caller, and treat a repeat hash inside a window as a duplicate.',
  '    pros:',
  '      - Nothing changes for existing clients',
  '      - No new client-side state',
  '    cons:',
  '      - Guesses at intent — two legitimate identical charges silently collapse into one',
  '      - Needs a body-hash index on every mutating route, not one header',
  '    verdict: Rejected — a payments API must never decide for the caller that a charge was a mistake.',
  '    tone: rejected',
  '  - title: Lean on the PSP',
  '    kicker: Rejected',
  '    how: Pass our order reference through and let the provider deduplicate.',
  '    pros:',
  '      - No code, no new dependency',
  '    cons:',
  '      - Five-minute window, shorter than our own retry backoff',
  '      - Our own writes still double up even when the charge does not',
  '      - Couples correctness to a vendor behaviour we do not control',
  '    verdict: Rejected — this is the status quo, and it is what produced the nine duplicates.',
  '    tone: rejected',
  '```',
  '',
  '## Architecture',
  '',
  '```block',
  'id: architecture',
  'title: Where the key is checked',
  'nodes:',
  '  - { id: client, col: 1, row: 1, kind: client, name: Mobile client }',
  '  - { id: api, col: 2, row: 1, kind: service, name: Payments API, tech: Go }',
  '  - { id: keys, col: 3, row: 1, kind: cache, name: Key store, tech: "Redis, 24h TTL" }',
  '  - { id: psp, col: 3, row: 2, kind: external, name: PSP }',
  'edges:',
  '  - { from: client, to: api, label: "POST /payments + key" }',
  '  - { from: api, to: keys, label: claim or replay }',
  '  - { from: api, to: psp, label: charge (first call only) }',
  '```',
  '',
  '## Consequences',
  '',
  '```statustable',
  'id: consequences',
  'columns: [Consequence, What it means for us]',
  'rows:',
  '  - { cells: ["Retries are safe by default", "Clients drop their bespoke retry guards; the SDK sends a UUID per user action"], status: completed }',
  '  - { cells: ["A new Redis dependency on the write path", "Payments now fails closed if the key store is down — capacity and alerting owned by Platform"], status: in progress }',
  '  - { cells: ["Keys expire after 24 hours", "A retry the next day charges again. Support needs the runbook line, and we watch the replay-rate metric"], status: todo }',
  '```',
  '',
  '## What could go wrong',
  '',
  '```risk',
  'id: adr-risks',
  'title: Risks we are accepting, and what we do about them',
  'items:',
  '  - { risk: Key store outage blocks every payment, likelihood: low, impact: high, mitigation: "Fail closed with 503 + Retry-After; Redis runs multi-AZ with a 60s failover drill each release", owner: Platform, status: mitigating }',
  '  - { risk: A client reuses one key for genuinely different charges, likelihood: med, impact: high, mitigation: Store a request fingerprint beside the key and return 422 when it disagrees, owner: Payments, status: mitigating }',
  '  - { risk: Clients never send the header, likelihood: med, impact: med, mitigation: "Log the miss rate per client; the header becomes required at v2", owner: Payments, status: open }',
  '```',
  '',
  '## Rollout',
  '',
  '```steps',
  'id: adr-rollout',
  'title: From merged to required',
  'items:',
  '  - title: Ship the middleware, keys optional',
  '    body: A request without a key behaves exactly as it does today, so nothing breaks on deploy.',
  '    code: PAYMENTS_IDEMPOTENCY=shadow',
  '    lang: bash',
  '  - title: Send keys from the SDKs',
  '    body: One UUID per user action, persisted with the pending payment so a cold start reuses it.',
  '    note: iOS and Android ship on their own cadence — expect six weeks before the miss rate flattens.',
  '  - title: Watch the replay rate',
  '    body: Replays should track the retry rate. A replay rate near zero means keys are being regenerated per attempt.',
  '    code: sum(rate(payments_idempotent_replay_total[5m])) by (client)',
  '    lang: promql',
  '  - title: Make the header required',
  '    body: Once the miss rate is under 1% for two weeks, missing keys get 400 on v2. v1 keeps the old behaviour until it is retired.',
  '```',
  '',
].join('\n');

const DESIGN_DOC_TEMPLATE = [
  '```meta',
  'title: Media processing off the upload path',
  'subtitle: A proposal to move thumbnailing and transcoding to an async pipeline.',
  'tag: RFC · Draft',
  '```',
  '',
  '## Problem',
  '',
  'Uploads block on media processing today: a 40 MB video holds an API worker',
  'for up to 90 seconds, and one slow transcode can starve the pool. Describe',
  'the pain in two to four sentences of plain prose — numbers beat adjectives.',
  '',
  '## Where the time goes',
  '',
  '```tree',
  'id: rfc-problem-breakdown',
  'variant: issue',
  'title: Why uploads are slow',
  'nodes:',
  '  - { id: root, label: Slow uploads }',
  '  - { id: cpu, parent: root, label: CPU-bound work }',
  '  - { id: io, parent: root, label: I/O-bound work }',
  '  - { id: c1, parent: cpu, label: Transcoding, note: "70% of wall time" }',
  '  - { id: c2, parent: cpu, label: Thumbnailing }',
  '  - { id: i1, parent: io, label: Object-store writes }',
  '```',
  '',
  '## Alternatives',
  '',
  '```options',
  'id: rfc-alternatives',
  'title: Approaches explored',
  'items:',
  '  - { kicker: Option 1, title: Bigger workers, how: Scale the API pool vertically., pros: [No code change], cons: [Cost scales with the worst upload, Still blocks the pool], verdict: "REJECTED — buys months, not a fix", tone: rejected }',
  '  - { kicker: Option 2, title: Async pipeline, how: "Accept the upload, enqueue processing, notify on completion.", pros: [Upload latency independent of media size, Retryable steps], cons: [Eventual consistency for previews], verdict: "CHOSEN — isolates the slow work", tone: chosen }',
  '```',
  '',
  '## Proposed design',
  '',
  '```block',
  'id: rfc-proposed-design',
  'title: The async pipeline',
  'nodes:',
  '  - { id: api, col: 1, row: 1, kind: service, name: Upload API, tech: Node }',
  '  - { id: q, col: 2, row: 1, kind: queue, name: media.jobs, tech: SQS }',
  '  - { id: worker, col: 3, row: 1, kind: service, name: Media worker, tech: ffmpeg }',
  '  - { id: s3, col: 2, row: 2, kind: store, name: Object store, tech: S3 }',
  'edges:',
  '  - { from: api, to: s3, label: raw upload }',
  '  - { from: api, to: q, label: enqueue }',
  '  - { from: q, to: worker, kind: dashed }',
  '  - { from: worker, to: s3, label: renditions }',
  '```',
  '',
  '## Behavior',
  '',
  '```sequence',
  'id: rfc-seq-upload',
  'title: One upload, end to end',
  'actors:',
  '  - { id: Client, name: Client }',
  '  - { id: API, name: Upload API }',
  '  - { id: Worker, name: Media worker }',
  'messages:',
  '  - { from: Client, to: API, label: POST /uploads, kind: sync }',
  '  - { from: API, to: Client, label: "202 Accepted + upload id", kind: response }',
  '  - { from: API, to: Worker, label: media.jobs message, kind: async }',
  '  - { from: Worker, to: Client, label: webhook media.ready, kind: async }',
  '```',
  '',
  '## Open questions',
  '',
  '```statustable',
  'id: rfc-open-questions',
  'title: To resolve before build',
  'columns: [Question, Where it stands]',
  'rows:',
  '  - { cells: ["Poison-pill handling — max retries before dead-letter?", "Needs a decision from the platform team"], status: todo }',
  '  - { cells: ["Do previews need a placeholder rendition synchronously?", "Prototype scheduled for next sprint"], status: todo }',
  '```',
  '',
].join('\n');

const RUNBOOK_TEMPLATE = [
  '```meta',
  'title: Runbook — elevated 5xx on the API',
  'subtitle: Triage and mitigate a 5xx spike on the public API.',
  'tag: Runbook · On-call',
  '```',
  '',
  '```callout',
  'tone: warn',
  'title: When to use this',
  'body: "The api-5xx-rate alert fired (>1% of requests over 5 minutes). If the whole site is down, use the total-outage runbook instead."',
  '```',
  '',
  '## Triage',
  '',
  '```flow',
  'id: rb-triage',
  'title: Decide which case you are in',
  'nodes:',
  '  - { id: start, col: 1, row: 1, kind: start, label: Alert fires }',
  '  - { id: deploy, col: 2, row: 1, kind: decision, label: "Deploy in last 30m?" }',
  '  - { id: rollback, col: 3, row: 1, kind: process, label: Roll back }',
  '  - { id: db, col: 2, row: 2, kind: decision, label: "DB latency high?" }',
  '  - { id: failover, col: 3, row: 2, kind: process, label: Fail over replica }',
  '  - { id: escalate, col: 2, row: 3, kind: end, label: Escalate to platform }',
  'edges:',
  '  - { from: start, to: deploy }',
  '  - { from: deploy, to: rollback, label: "yes" }',
  '  - { from: deploy, to: db, label: "no" }',
  '  - { from: db, to: failover, label: "yes" }',
  '  - { from: db, to: escalate, label: "no", kind: error }',
  '```',
  '',
  '## Act',
  '',
  '```steps',
  'id: rb-mitigation',
  'title: Roll back the last deploy',
  'items:',
  '  - title: Confirm the suspect release',
  '    body: The release that started serving right before the spike.',
  '    code: kubectl rollout history deploy/api | tail -3',
  '    lang: bash',
  '  - title: Roll back',
  '    code: kubectl rollout undo deploy/api',
  '    lang: bash',
  '    note: Rollback takes ~3 minutes to settle; watch the error rate, not the pods.',
  '  - title: Verify',
  '    body: 5xx rate should drop below 0.1% within five minutes.',
  '    code: curl -s https://status.internal/api/error-rate',
  '    lang: bash',
  '```',
  '',
  '## Symptom → action',
  '',
  '```table',
  'id: rb-symptom-action',
  'columns: [Symptom, Likely cause, Action]',
  'rows:',
  '  - ["5xx only on POST /orders", "Payment provider degraded", "Enable the capture circuit breaker"]',
  '  - ["Timeouts across all routes", "DB primary saturated", "Fail over to the replica"]',
  '  - ["Spike right after a deploy", "Bad release", "Roll back (steps above)"]',
  '```',
  '',
].join('\n');

const ROADMAP_TEMPLATE = [
  '```meta',
  'title: Payments platform — H2 roadmap',
  'subtitle: What ships when, and the targets each phase moves.',
  'tag: Roadmap · H2',
  '```',
  '',
  '## Targets',
  '',
  '```stats',
  'id: rm-targets',
  'title: Where H2 should land',
  'stats:',
  '  - { value: "99.95%", label: Checkout availability, delta: "+0.15pp", trend: up }',
  '  - { value: "600ms", label: Checkout p95, delta: "-1.8s", trend: up }',
  '  - { value: "3", label: New payment methods, trend: flat }',
  '```',
  '',
  '## Phases',
  '',
  '```timeline',
  'id: rm-phases',
  'items:',
  '  - { label: Async capture, date: Jul, status: done, desc: Capture moves off the request path. }',
  '  - { label: Wallets, date: Aug-Sep, status: current, desc: Apple Pay + Google Pay behind a flag. }',
  '  - { label: Bank transfers, date: Oct, status: next, desc: SEPA + ACH via the PSP. }',
  '  - { label: Chargeback automation, date: Nov-Dec, status: future, desc: Evidence packets built from order data. }',
  '```',
  '',
  '## Now / next / later',
  '',
  '```kanban',
  'id: rm-board',
  'columns:',
  '  - label: Now',
  '    cards:',
  '      - { title: Wallet tokenization, tag: wallets }',
  '      - { title: Capture worker autoscaling }',
  '  - label: Next',
  '    cards:',
  '      - { title: SEPA mandate flow, tag: transfers }',
  '  - label: Later',
  '    cards:',
  '      - { title: Chargeback evidence builder }',
  '```',
  '',
  '## Workstreams',
  '',
  '```statustable',
  'id: rm-workstreams',
  'columns: [Workstream, Latest update]',
  'statuses:',
  '  - { label: on track, color: green }',
  '  - { label: at risk, color: amber }',
  'rows:',
  '  - { cells: [Wallets GA behind a flag, "Payments — tokenization in canary, due Sep 15"], status: on track }',
  '  - { cells: [PSP contract for bank transfers, "Finance — redlines back from legal, due Aug 30"], status: at risk }',
  '  - { cells: [Deprecate the legacy capture job, "Payments — blocked until wallets GA"], status: todo }',
  '```',
  '',
].join('\n');

const API_SPEC_TEMPLATE = [
  '```meta',
  'title: Sessions API',
  'subtitle: Create and inspect login sessions for first-party clients.',
  'tag: API · v1',
  '```',
  '',
  'All routes are under `https://api.example.com/v1` and require a client key.',
  '',
  '## Create a session',
  '',
  '```endpoint',
  'id: post-sessions',
  'method: POST',
  'path: /sessions',
  'description: Exchange user credentials for a session token.',
  'auth: Client key (X-Client-Key header)',
  'body:',
  '  - { name: email, type: string, required: true, desc: Account email }',
  '  - { name: password, type: string, required: true, desc: Account password }',
  '  - { name: remember, type: boolean, desc: Extend the session to 30 days }',
  'responses:',
  '  - { status: 201, desc: Session created }',
  '  - { status: 401, desc: Bad credentials }',
  '  - { status: 429, desc: Too many attempts — retry after the indicated delay }',
  'request: |',
  '  { "email": "sam@example.com", "password": "…", "remember": true }',
  'response: |',
  '  { "token": "ses_9f2…", "expiresAt": "2026-08-01T12:00:00Z" }',
  '```',
  '',
  '## Request flow',
  '',
  '```sequence',
  'id: sessions-seq-create',
  'title: Credential exchange',
  'endpoint: { method: POST, path: /sessions }',
  'actors:',
  '  - { id: Client, name: Client }',
  '  - { id: API, name: Sessions API }',
  '  - { id: IDP, name: Identity store }',
  'messages:',
  '  - { from: Client, to: API, label: POST /sessions, kind: sync }',
  '  - { from: API, to: IDP, label: verify credentials, kind: sync }',
  '  - { from: IDP, to: API, label: user record, kind: response }',
  '  - { from: API, to: Client, label: "201 + session token", kind: response }',
  '```',
  '',
  '## Data touched',
  '',
  '```erd',
  'id: sessions-model',
  'entities:',
  '  - name: users',
  '    columns:',
  '      - { name: id, type: uuid, pk: true }',
  '      - { name: email, type: text }',
  '  - name: sessions',
  '    columns:',
  '      - { name: id, type: uuid, pk: true }',
  '      - { name: user_id, type: uuid, fk: true }',
  '      - { name: expires_at, type: timestamptz }',
  'relations:',
  '  - { from: users, to: sessions, label: has, card: "1:N" }',
  '```',
  '',
  '## Status codes',
  '',
  '```table',
  'id: sessions-status-codes',
  'columns: [Status, Meaning, Client action]',
  'rows:',
  '  - [201, Session created, Store the token]',
  '  - [401, Bad credentials, Prompt the user again]',
  '  - [429, Rate limited, "Retry after the Retry-After header"]',
  '```',
  '',
].join('\n');

const SYSTEM_DESIGN_TEMPLATE = [
  '```meta',
  'title: Webhook delivery service',
  'subtitle: Design for delivering customer webhooks reliably at platform scale.',
  'tag: System design · Draft',
  '```',
  '',
  '## Requirements',
  '',
  '```drivers',
  'id: wh-requirements',
  'title: What the design must satisfy',
  'items:',
  '  - { title: At-least-once delivery, body: Every event reaches every subscribed endpoint., tag: "MUST", icon: check, accent: green }',
  '  - { title: Ordered per subscription, body: Events for one subscription arrive in order., tag: "MUST", icon: layers, accent: blue }',
  '  - { title: Slow consumers isolated, body: One dead endpoint never delays the rest., tag: "MUST", icon: shield, accent: purple }',
  '  - { title: Replay window, body: Customers can replay the last 7 days., tag: "SHOULD", icon: clock, accent: amber }',
  '```',
  '',
  '## Envelope math',
  '',
  '```envelope',
  'id: wh-envelope',
  'title: Delivery-path capacity',
  'assumptions:',
  '  - { label: Events per day, value: 40M }',
  '  - { label: Subscriptions per event, value: "1.5 avg" }',
  'steps:',
  '  - { label: Deliveries per day, calc: "40M × 1.5", result: 60M/day }',
  '  - { label: Steady QPS, calc: "60M / 86,400 s", result: "≈ 700 rps" }',
  '  - { label: Peak QPS, calc: "700 × 4 (bursts)", result: "≈ 2,800 rps" }',
  'result: { label: Provision for, value: "~5,600 rps (2× peak headroom)" }',
  '```',
  '',
  '## Contract',
  '',
  '```endpoint',
  'id: post-subscriptions',
  'method: POST',
  'path: /webhook-subscriptions',
  'title: Subscribe to events',
  'body:',
  '  - { name: url, type: string, required: true, desc: HTTPS endpoint to deliver to }',
  '  - { name: events, type: "string[]", required: true, desc: Event types to receive }',
  'responses:',
  '  - { status: 201, desc: Subscription created }',
  '  - { status: 422, desc: URL failed the handshake ping }',
  '```',
  '',
  '## High level',
  '',
  '```block',
  'id: wh-topology',
  'preset: infra',
  'title: Delivery topology',
  'systemLabel: webhooks · production',
  'layers:',
  '  - { label: Ingest }',
  '  - { label: Queueing }',
  '  - { label: Delivery }',
  'nodes:',
  '  - { id: api, layer: 0, kind: service, name: Events API, tech: Go }',
  '  - { id: log, layer: 1, kind: queue, name: event log, tech: Kafka }',
  '  - { id: sched, layer: 2, kind: service, name: Scheduler, tech: per-subscription queues }',
  '  - { id: sender, layer: 2, kind: service, name: Senders, tech: HTTP workers }',
  '  - { id: store, layer: 1, kind: store, name: delivery state, tech: Postgres }',
  'edges:',
  '  - { from: api, to: log }',
  '  - { from: log, to: sched }',
  '  - { from: sched, to: sender }',
  '  - { from: sender, to: store, kind: dashed, label: attempts }',
  '```',
  '',
  '## The bottleneck — slow consumers',
  '',
  '```options',
  'id: wh-isolation-options',
  'title: Isolating slow endpoints',
  'items:',
  '  - { kicker: Option 1, title: Shared worker pool, how: All deliveries through one pool with timeouts., pros: [Simple], cons: [One stuck endpoint consumes the pool], verdict: "REJECTED — fails isolation", tone: rejected }',
  '  - { kicker: Option 2, title: Per-subscription queues, how: Scheduler drains each subscription independently with backoff., pros: [Head-of-line blocking scoped to one customer, Natural per-endpoint rate limits], cons: [More queue state to manage], verdict: "CHOSEN", tone: chosen }',
  '```',
  '',
  '## Delivery objectives',
  '',
  '```slo',
  'id: wh-slos',
  'items:',
  '  - { name: Delivery latency, sli: Deliveries attempted under 60 s of event time, target: "99%", current: "99.4%", window: 30d, budget: 0.4 }',
  '  - { name: Delivery success, sli: Deliveries succeeding within the retry policy, target: "99.9%", window: 30d, budget: 0.2 }',
  '```',
  '',
  '## Plan',
  '',
  '```timeline',
  'id: wh-plan',
  'items:',
  '  - { label: Ingest + log, date: Q3, status: current, desc: Events API writing to the log. }',
  '  - { label: Scheduler + senders, date: Q3, status: next, desc: Per-subscription delivery with backoff. }',
  '  - { label: Replay API, date: Q4, status: future, desc: 7-day replay from the log. }',
  '```',
  '',
].join('\n');

const AGENT_SYSTEM_TEMPLATE = [
  '```meta',
  'title: Support triage agent',
  'subtitle: How the ticket-triage agent works — loop, prompts, budget, and evals.',
  'tag: Agent system · v1',
  '```',
  '',
  '## Requirements',
  '',
  '```drivers',
  'id: agent-requirements',
  'title: What the agent must do',
  'items:',
  '  - { title: Resolve or route, body: Answer from the KB or escalate to the right queue., tag: "JOB", icon: check, accent: green }',
  '  - { title: Grounded answers, body: Every claim cites a KB article., tag: "GUARDRAIL", icon: shield, accent: purple }',
  '  - { title: Bounded cost, body: "One episode stays under 40k tokens.", tag: "BUDGET", icon: bolt, accent: amber }',
  '```',
  '',
  '## The loop',
  '',
  '```agentloop',
  'id: agent-loop',
  'title: Triage loop',
  'agent:',
  '  name: Triage agent',
  '  model: claude-sonnet-4-6',
  '  note: Routes each ticket to a fix or a human.',
  'env: Customer',
  'tools:',
  '  - { name: search_kb, desc: Search help-center articles }',
  '  - { name: get_account, desc: Look up plan and billing state }',
  '  - { name: create_ticket, desc: Escalate to a human queue }',
  'memory:',
  '  - conversation history',
  '  - customer profile',
  'stop: reply sent or ticket escalated',
  '```',
  '',
  '## Prompt anatomy',
  '',
  '```prompt',
  'id: agent-prompt',
  'title: Triage prompt',
  'segments:',
  '  - kind: system',
  '    label: role + guardrails',
  '    text: "You are a support agent for {{product}}. Answer only from KB articles; cite the article id."',
  '  - kind: user',
  '    text: "Customer ({{plan}} plan) writes: {{ticket}}"',
  'vars:',
  '  - { name: product, desc: Product name from config }',
  '  - { name: plan, desc: Plan tier of the customer }',
  '  - { name: ticket, desc: The inbound ticket body }',
  '```',
  '',
  '## Context budget',
  '',
  '```context',
  'id: agent-budget',
  'title: Where one episode\'s window goes',
  'window: 200000',
  'segments:',
  '  - { label: system prompt, tokens: 4000, accent: navy }',
  '  - { label: tool schemas, tokens: 6000, accent: teal }',
  '  - { label: KB retrieval, tokens: 18000, accent: amber }',
  '  - { label: history, tokens: 12000, accent: purple }',
  '```',
  '',
  '## One turn, end to end',
  '',
  '```sequence',
  'id: agent-seq-turn',
  'title: A tool-using turn',
  'actors:',
  '  - { id: User, name: Customer }',
  '  - { id: Agent, name: Agent }',
  '  - { id: KB, name: search_kb }',
  'messages:',
  '  - { from: User, to: Agent, label: ticket text, kind: sync }',
  '  - { from: Agent, to: KB, label: "search_kb(query)", kind: sync }',
  '  - { from: KB, to: Agent, label: top 3 articles, kind: response }',
  '  - { from: Agent, to: User, label: cited reply, kind: response }',
  '```',
  '',
  '## A real episode',
  '',
  '```trace',
  'id: agent-episode',
  'title: Password reset — one episode',
  'turns:',
  '  - role: user',
  '    text: I never get the reset email.',
  '  - role: assistant',
  '    thinking: Could be a bounce — check delivery before blaming spam.',
  '    text: Let me check our email logs.',
  '  - role: tool',
  '    tool: search_kb',
  '    args: \'{ "query": "reset email not delivered" }\'',
  '    result: "KB-142: bounced mail troubleshooting"',
  '  - role: assistant',
  '    text: "Your mailbox rejected the email (KB-142) — free up space and I will resend it."',
  '```',
  '',
  '## Eval results',
  '',
  '```table',
  'id: agent-evals',
  'columns: [Eval, Target, Current]',
  'rows:',
  '  - [Resolution without escalation, "40%", "46%"]',
  '  - [Citation accuracy, "99%", "98.7%"]',
  '  - ["Tokens per episode (p95)", "40k", "31k"]',
  '```',
  '',
].join('\n');

const DESIGN_SYSTEM_TEMPLATE = [
  '```meta',
  'title: Aurora design system',
  'subtitle: Tokens, type, usage rules, and component status for product teams.',
  'tag: Design system · v2',
  '```',
  '',
  '## Color tokens',
  '',
  '```palette',
  'id: ds-tokens',
  'title: Core palette',
  'cols: 4',
  'colors:',
  '  - { name: Primary, value: "#0E54A1", usage: Buttons and links }',
  '  - { name: Ink, value: "#1F2937", usage: Body text }',
  '  - { name: Surface, value: "#F6F8FB", usage: Card backgrounds }',
  '  - { name: Positive, value: "#1F9747", usage: Success states }',
  '```',
  '',
  '## Type scale',
  '',
  '```typescale',
  'id: ds-type',
  'items:',
  '  - { name: Display, size: 40, weight: 700, font: display }',
  '  - { name: Heading, size: 24, weight: 700, font: display }',
  '  - { name: Body, size: 15, lineHeight: 1.6 }',
  '  - { name: Caption, size: 12, weight: 500, note: secondary text }',
  '```',
  '',
  '## Usage guidelines',
  '',
  '```dodont',
  'id: ds-button-usage',
  'title: Button usage',
  'dos:',
  '  - { text: Use one primary button per view }',
  '  - { text: Write labels as verbs, example: "Save changes" }',
  'donts:',
  '  - { text: Stack two primary buttons side by side }',
  '  - { text: Disable a button without explaining why, example: "tooltip: Add a line item first" }',
  '```',
  '',
  '## Component status',
  '',
  '```inventory',
  'id: ds-components',
  'title: Component inventory',
  'items:',
  '  - { name: Button, status: stable, tag: v2 }',
  '  - { name: Data table, status: beta, note: API may change before GA }',
  '  - { name: Date picker, status: experimental }',
  '  - { name: Modal (legacy), status: deprecated, note: Use Dialog instead }',
  '```',
  '',
  '## Key screen',
  '',
  '```wireframe',
  'id: ds-key-screen',
  'title: The settings pattern',
  'screens:',
  '  - device: browser',
  '    title: Settings',
  '    url: app.example.com/settings',
  '    elements:',
  '      - { type: nav, label: "Profile, Billing, Team" }',
  '      - { type: header, label: Billing }',
  '      - { type: list, rows: 3 }',
  '      - { type: button, label: Update plan }',
  '```',
  '',
].join('\n');

const POSTMORTEM_TEMPLATE = [
  '```meta',
  'title: Postmortem — checkout outage 2026-06-12',
  'subtitle: 41 minutes of failed checkouts caused by an expired PSP certificate.',
  'tag: Postmortem · SEV-1 · Resolved',
  '```',
  '',
  '```callout',
  'id: pm-impact',
  'tone: danger',
  'title: Impact',
  'body: "41 minutes of checkout failures (14:03-14:44 UTC). ~3,100 failed purchases, ~$46k delayed revenue. No data loss; retried payments settled by 16:00."',
  '```',
  '',
  '## Timeline',
  '',
  '```timeline',
  'id: pm-timeline',
  'items:',
  '  - { label: Cert expires, date: "14:03", status: done, desc: PSP client certificate lapses; captures start failing. }',
  '  - { label: Alert fires, date: "14:07", status: done, desc: checkout-error-rate pages the on-call. }',
  '  - { label: Root cause found, date: "14:31", status: done, desc: TLS handshake errors traced to the expired cert. }',
  '  - { label: Mitigated, date: "14:44", status: done, desc: Renewed cert deployed; error rate back to baseline. }',
  '```',
  '',
  '## Root cause',
  '',
  '```tree',
  'id: pm-root-cause',
  'variant: issue',
  'title: Why checkouts failed',
  'nodes:',
  '  - { id: root, label: Checkout failures }',
  '  - { id: trigger, parent: root, label: Trigger }',
  '  - { id: defense, parent: root, label: Missing defenses }',
  '  - { id: t1, parent: trigger, label: PSP cert expired, note: issued 2025-06-12 }',
  '  - { id: d1, parent: defense, label: No expiry monitoring }',
  '  - { id: d2, parent: defense, label: No capture fallback path }',
  '```',
  '',
  '## Action items',
  '',
  '```statustable',
  'id: pm-actions',
  'title: Corrective actions',
  'columns: [Action, Owner / due]',
  'rows:',
  '  - { cells: [Alert on certs expiring within 21 days, "Platform — due Jun 26"], status: in progress }',
  '  - { cells: [Automate PSP cert rotation, "Payments — due Jul 15"], status: todo }',
  '  - { cells: [Queue captures when the PSP is unreachable, "Payments — needs sizing"], status: todo }',
  '```',
  '',
].join('\n');

const DATA_MODEL_TEMPLATE = [
  '```meta',
  'title: Orders data model',
  'subtitle: The tables behind ordering, and the lifecycle of an order row.',
  'tag: Data model · v1',
  '```',
  '',
  '## Entities',
  '',
  '```erd',
  'id: orders-erd',
  'title: Orders and their line items',
  'entities:',
  '  - name: users',
  '    columns:',
  '      - { name: id, type: uuid, pk: true }',
  '      - { name: email, type: text }',
  '  - name: orders',
  '    columns:',
  '      - { name: id, type: uuid, pk: true }',
  '      - { name: user_id, type: uuid, fk: true }',
  '      - { name: status, type: order_status }',
  '      - { name: total_cents, type: bigint }',
  '  - name: order_items',
  '    columns:',
  '      - { name: id, type: uuid, pk: true }',
  '      - { name: order_id, type: uuid, fk: true }',
  '      - { name: sku, type: text }',
  '      - { name: qty, type: int }',
  'relations:',
  '  - { from: users, to: orders, label: places, card: "1:N" }',
  '  - { from: orders, to: order_items, label: contains, card: "1:N" }',
  '```',
  '',
  '## Field semantics',
  '',
  '```table',
  'id: orders-field-semantics',
  'columns: [Field, Semantics]',
  'rows:',
  '  - [orders.status, "Enum order_status — see the lifecycle below; only the state machine writes it"]',
  '  - [orders.total_cents, "Integer cents, never floats; recomputed from items on every mutation"]',
  '  - [order_items.sku, "Denormalized from the catalog at purchase time — price changes never rewrite history"]',
  '```',
  '',
  '## Record lifecycle',
  '',
  '```state',
  'id: order-lifecycle',
  'title: order_status transitions',
  'states:',
  '  - { id: s0, col: 1, row: 1, kind: start }',
  '  - { id: pending, col: 2, row: 1, kind: wait, name: PENDING }',
  '  - { id: paid, col: 3, row: 1, kind: active, name: PAID }',
  '  - { id: shipped, col: 4, row: 1, kind: active, name: SHIPPED }',
  '  - { id: done, col: 5, row: 1, kind: terminal }',
  '  - { id: cancelled, col: 3, row: 2, kind: terminal, name: CANCELLED }',
  'transitions:',
  '  - { from: s0, to: pending, event: create }',
  '  - { from: pending, to: paid, event: capture }',
  '  - { from: pending, to: cancelled, event: "cancel / timeout" }',
  '  - { from: paid, to: shipped, event: fulfil }',
  '  - { from: shipped, to: done, event: deliver }',
  '```',
  '',
].join('\n');

const DECK_TEMPLATE = [
  '```meta',
  'title: Fixing checkout latency',
  'subtitle: What we changed, what it bought us, and what we do next.',
  'tag: Deck · Eng review',
  '```',
  '',
  '## Part 1 — the problem',
  '',
  '```divider',
  'kicker: PART 1',
  'title: Checkout was bleeding conversions',
  'accent: navy',
  '```',
  '',
  '## The synchronous capture call dominated checkout time {split}',
  '',
  'Every 100ms of checkout latency costs ~0.6% conversion. Our p95 had',
  'drifted to 2.4s — and one call was 71% of it.',
  '',
  '```chart',
  'id: deck-latency-breakdown',
  'kind: bar',
  'title: Where the 2.4s went',
  'unit: ms',
  'labels: [Gateway, Fraud, Capture, Persist, Render]',
  'series:',
  '  - { label: p95 ms, accent: navy, values: [120, 260, 1700, 180, 140] }',
  '```',
  '',
  '## Part 2 — the fix',
  '',
  '```divider',
  'kicker: PART 2',
  'title: Move capture off the request path',
  'accent: teal',
  '```',
  '',
  '## One number tells the story {split}',
  '',
  'The async capture change removed the 1.7s synchronous call from the',
  'request path. Nothing else shipped in the window.',
  '',
  '```bignumber',
  'id: deck-money-slide',
  'value: "-75%"',
  'label: Checkout p95 after the change',
  'context: "2.4s → 600ms over four weeks of production traffic"',
  'trend: down',
  'accent: green',
  '```',
  '',
  '## What we do next {split}',
  '',
  'The same pattern applies to every synchronous third-party call on the',
  'hot path — fraud scoring is the next candidate.',
  '',
  '```timeline',
  'id: deck-next-steps',
  'items:',
  '  - { label: Async capture, date: shipped, status: done }',
  '  - { label: Fraud scoring async, date: Q3, status: current }',
  '  - { label: Hot-path audit, date: Q4, status: next }',
  '```',
  '',
  '## What to remember',
  '',
  '```takeaways',
  'id: deck-closing',
  'items:',
  '  - text: The synchronous capture call was the bottleneck',
  '    detail: It accounted for 71% of the 2.4s checkout p95.',
  '  - text: Moving it to a queue cut p95 by 75%',
  '  - text: Conversion recovered within two weeks',
  '  - text: Audit every synchronous third-party call on the hot path',
  '```',
  '',
].join('\n');

const MIGRATION_PLAN_TEMPLATE = [
  '```meta',
  'title: Orders MySQL → Postgres',
  'subtitle: Dual-write, backfill, verify, cut over — with a rollback that stays open until the end.',
  'tag: Migration · In flight',
  '```',
  '',
  '```callout',
  'tone: warn',
  'title: The one rule',
  'body: "Rollback stays possible until the final step. Every phase below is reversible on its own, and nothing deletes the MySQL data until two weeks after cutover."',
  '```',
  '',
  '## Where we are, where we land',
  '',
  '```cvt',
  'id: mig-shape',
  'title: What actually changes',
  'current:',
  '  label: MySQL 5.7 (today)',
  '  items:',
  '    - Single primary, vertical scaling only — already on the largest instance',
  '    - No native JSON indexing, so the order metadata is a serialized blob',
  '    - Schema changes lock the table; releases wait for a maintenance window',
  '    - Read replicas lag 4-9s under load, so reporting reads the primary',
  'target:',
  '  label: Postgres 16 (after)',
  '  items:',
  '    - Primary + two replicas, logical replication for zero-downtime upgrades',
  '    - jsonb with GIN indexes — meta queries stop being full scans',
  '    - Non-blocking DDL for the changes we make weekly',
  '    - Replicas under 500ms, so reporting moves off the primary',
  'note: The application data model does not change. This is an engine migration, not a rewrite.',
  '```',
  '',
  '## Phases',
  '',
  '```timeline',
  'id: mig-phases',
  'items:',
  '  - { label: Schema parity, date: Week 1, status: done, desc: Postgres schema generated and diffed against MySQL in CI. }',
  '  - { label: Dual write, date: Week 2-3, status: current, desc: Writes go to both engines; MySQL stays authoritative. }',
  '  - { label: Backfill + verify, date: Week 4, status: next, desc: "Historic rows copied, then row-count and checksum comparison per table." }',
  '  - { label: Read cutover, date: Week 5, status: next, desc: "Reads move to Postgres behind a flag, one endpoint at a time." }',
  '  - { label: Write cutover, date: Week 6, status: future, desc: "Postgres becomes authoritative; MySQL keeps receiving writes as the escape hatch." }',
  '  - { label: Decommission, date: Week 8, status: future, desc: "MySQL writes stop and the instance is snapshotted, then retired." }',
  '```',
  '',
  '## Cutover runbook',
  '',
  '```steps',
  'id: mig-cutover',
  'title: The 20-minute window',
  'items:',
  '  - title: Freeze writes at the edge',
  '    body: The API returns 503 with Retry-After for mutating routes. Reads keep serving from Postgres.',
  '    code: kubectl -n orders set env deploy/orders-api WRITE_FREEZE=1',
  '    lang: bash',
  '    note: Clients retry automatically. Anything longer than 90 seconds shows in the checkout funnel.',
  '  - title: Drain in-flight writes',
  '    body: Wait for the dual-write queue to reach zero before comparing anything.',
  '    code: "psql -c \\"select count(*) from replication_lag where behind_ms > 0\\""',
  '    lang: bash',
  '  - title: Verify the two engines agree',
  '    body: Row counts and per-table checksums must match exactly. A mismatch aborts the cutover — this is the go/no-go.',
  '    code: ./scripts/verify-parity.sh --strict',
  '    lang: bash',
  '  - title: Promote Postgres',
  '    body: Flip the authority flag. MySQL keeps taking writes so a rollback is still one flag away.',
  '    code: kubectl -n orders set env deploy/orders-api DB_AUTHORITY=postgres WRITE_FREEZE=0',
  '    lang: bash',
  '  - title: Watch for 30 minutes',
  '    body: Error rate, checkout conversion and p95 all back to baseline before anyone leaves the call.',
  '```',
  '',
  '## If it goes wrong',
  '',
  '```flow',
  'id: mig-rollback',
  'title: Rollback decision',
  'nodes:',
  '  - { id: start, col: 1, row: 1, kind: start, label: Something looks wrong }',
  '  - { id: data, col: 2, row: 1, kind: decision, label: "Data mismatch?" }',
  '  - { id: back, col: 3, row: 1, kind: process, label: "DB_AUTHORITY=mysql" }',
  '  - { id: perf, col: 2, row: 2, kind: decision, label: "Latency only?" }',
  '  - { id: tune, col: 3, row: 2, kind: process, label: Raise pool + reindex }',
  '  - { id: done, col: 2, row: 3, kind: end, label: Hold and monitor }',
  'edges:',
  '  - { from: start, to: data }',
  '  - { from: data, to: back, label: "yes", kind: error }',
  '  - { from: data, to: perf, label: "no" }',
  '  - { from: perf, to: tune, label: "yes" }',
  '  - { from: perf, to: done, label: "no" }',
  '```',
  '',
  '## Risks',
  '',
  '```risk',
  'id: mig-risks',
  'items:',
  '  - { risk: Silent data divergence during dual write, likelihood: med, impact: high, mitigation: Per-table checksums run hourly and gate the cutover, owner: Data, status: mitigating }',
  '  - { risk: Query plans regress on Postgres, likelihood: high, impact: med, mitigation: Top 40 queries replayed against a production-sized copy; two rewritten already, owner: Orders, status: mitigating }',
  '  - { risk: Cutover window overruns, likelihood: low, impact: high, mitigation: Rehearsed twice against a restored snapshot — last run took 11 minutes, owner: Orders, status: closed }',
  '  - { risk: Reporting jobs still point at MySQL, likelihood: med, impact: low, mitigation: Connection strings inventoried; four jobs left to move, owner: Analytics, status: open }',
  '```',
  '',
  '## Tracking',
  '',
  '```statustable',
  'id: mig-tracking',
  'columns: [Workstream, Latest]',
  'rows:',
  '  - { cells: [Schema parity in CI, "Green for 9 days — diff runs on every PR"], status: completed }',
  '  - { cells: [Dual write in production, "Live for all writes; queue depth steady under 200"], status: in progress }',
  '  - { cells: [Backfill of 240M historic rows, "Runs nightly in 6h batches — 61% complete"], status: in progress }',
  '  - { cells: [Query plan review, "Two rewrites merged, 6 of 40 queries left"], status: in progress }',
  '  - { cells: [Reporting jobs moved, "Blocked on the Analytics migration window"], status: blocked }',
  '```',
  '',
].join('\n');

const THREAT_MODEL_TEMPLATE = [
  '```meta',
  'title: Threat model — public share links',
  'subtitle: Anyone with the URL can read the file. What that lets an attacker do, and what stops them.',
  'tag: Security · Reviewed 2026-02-18',
  '```',
  '',
  '## Scope',
  '',
  '```spec',
  'id: tm-scope',
  'title: What is being modelled',
  'rows:',
  '  - { label: Feature, value: Public share links for uploaded files }',
  '  - { label: Assets, value: File contents · file names · uploader identity · the link itself }',
  '  - { label: Trust boundary, value: The public internet reaches the share service directly }',
  '  - { label: Attacker, value: "Unauthenticated, has a link or can guess one · a logged-in user of another tenant" }',
  '  - { label: Out of scope, value: Physical access · the CI supply chain · the S3 control plane }',
  '  - { label: Reviewed by, value: Security + Platform · next review at GA }',
  '```',
  '',
  '## Data flow',
  '',
  '```dfd',
  'id: tm-flow',
  'title: Where the data crosses the boundary',
  'groups:',
  '  - { id: pub, col: 1, row: 1, cols: 1, rows: 2, label: Untrusted, color: red }',
  '  - { id: svc, col: 2, row: 1, cols: 2, rows: 2, label: Our infrastructure, color: teal }',
  'nodes:',
  '  - { id: visitor, col: 1, row: 1, name: Link visitor, kind: external }',
  '  - { id: owner, col: 1, row: 2, name: File owner, kind: external }',
  '  - { id: share, col: 2, row: 1, name: Share service, kind: process, num: "1" }',
  '  - { id: tokens, col: 3, row: 1, name: Link tokens, kind: datastore }',
  '  - { id: files, col: 3, row: 2, name: Object store, kind: datastore }',
  'edges:',
  '  - { from: visitor, to: share, label: "GET /s/{token}" }',
  '  - { from: share, to: tokens, label: resolve + check expiry }',
  '  - { from: share, to: files, label: "signed URL, 60s" }',
  '  - { from: owner, to: share, label: create / revoke link }',
  '```',
  '',
  '## Threats',
  '',
  '```risk',
  'id: tm-threats',
  'title: STRIDE, applied to the flow above',
  'items:',
  '  - { risk: "Token guessing — enumerate /s/{token} until something resolves", likelihood: high, impact: high, mitigation: "128-bit random tokens, no sequence; 20 req/min/IP; alert on a 404 burst", owner: Platform, status: mitigating }',
  '  - { risk: Signed URL leaks via Referer to a third-party page, likelihood: med, impact: high, mitigation: "Referrer-Policy: no-referrer on the download route; URLs expire in 60 seconds", owner: Platform, status: mitigating }',
  '  - { risk: Revoked link keeps working from cache, likelihood: med, impact: high, mitigation: Revocation writes a tombstone the CDN honours; TTL capped at 30s, owner: Share, status: open }',
  '  - { risk: Uploader identity inferred from the file name, likelihood: med, impact: low, mitigation: Served under an opaque path with the original name only in Content-Disposition, owner: Share, status: accepted }',
  '  - { risk: Stored XSS from an HTML upload rendered inline, likelihood: med, impact: high, mitigation: "Content-Disposition: attachment plus a sandbox CSP on the download origin", owner: Share, status: mitigating }',
  '  - { risk: Denial of wallet — a hot link drives egress cost, likelihood: low, impact: med, mitigation: Per-link bandwidth cap; the link parks itself after 50GB, owner: Platform, status: open }',
  '```',
  '',
  '## Controls in place',
  '',
  '```list',
  'id: tm-controls',
  'style: check',
  'title: What already stops these',
  'items:',
  '  - { lead: 128-bit tokens, text: Generated with a CSPRNG — guessing is not a practical attack, done: true }',
  '  - { lead: Short-lived signed URLs, text: "60-second expiry, so a leaked URL is worthless by the time it is shared", done: true }',
  '  - { lead: Downloads on a separate origin, text: "No session cookie exists there, so a malicious upload cannot reach an authenticated context", done: true }',
  '  - { lead: Rate limit + burst alert, text: "20 requests/min/IP, and a 404 burst pages the on-call", done: true }',
  '  - { lead: CDN revocation tombstones, text: "Revocation has to invalidate the edge, not just the origin", done: false }',
  '  - { lead: Per-link bandwidth cap, text: Cost control against a link that goes viral, done: false }',
  '```',
  '',
  '## What we test',
  '',
  '```table',
  'id: tm-tests',
  'columns: [Test, Expected, Where]',
  'rows:',
  '  - ["Request 10k random tokens", { v: "All 404, IP blocked after 20", tone: pos }, "e2e/share-enumeration"]',
  '  - ["Fetch a signed URL after 61s", { v: "403 from the object store", tone: pos }, "e2e/share-expiry"]',
  '  - ["Download an uploaded .html", { v: "Content-Disposition: attachment", tone: pos }, "e2e/share-content-type"]',
  '  - ["Revoke, then fetch through the CDN", { v: "404 within 30s", tone: warn }, "manual — automation pending"]',
  '```',
  '',
].join('\n');

const SERVICE_OVERVIEW_TEMPLATE = [
  '```meta',
  'title: orders-api',
  'subtitle: Owns the order lifecycle from cart submission to fulfilment handoff.',
  'tag: Service · Tier 1',
  '```',
  '',
  '## At a glance',
  '',
  '```spec',
  'id: svc-facts',
  'title: The facts you need at 3am',
  'accent: navy',
  'rows:',
  '  - { label: Owner, value: "Orders team · #team-orders" }',
  '  - { label: On-call, value: PagerDuty schedule orders-primary }',
  '  - { label: Repo, value: github.com/acme/orders-api }',
  '  - { label: Runtime, value: "Go 1.23 · Kubernetes · 12 pods, HPA to 40" }',
  '  - { label: Datastores, value: "Postgres (orders) · Redis (idempotency) · SQS (fulfilment)" }',
  '  - { label: Dashboards, value: Grafana Orders-overview · Honeycomb dataset orders-api }',
  '  - { label: Deploy, value: "Merge to main → canary 10% → full, roughly 18 minutes" }',
  '  - { label: Tier, value: "Tier 1 — customer-facing, revenue path" }',
  '```',
  '',
  '## What it does',
  '',
  'Accepts a submitted cart, prices it, reserves stock, takes payment through the',
  'payments service, and hands a confirmed order to fulfilment. It owns order',
  'state; nothing else writes the `orders` table. Everything downstream reacts to',
  'the `order.confirmed` event rather than calling back in.',
  '',
  '```block',
  'id: svc-arch',
  'title: What it talks to',
  'nodes:',
  '  - { id: web, col: 1, row: 1, kind: client, name: Storefront }',
  '  - { id: api, col: 2, row: 1, kind: service, name: orders-api, tech: Go }',
  '  - { id: pay, col: 3, row: 1, kind: service, name: payments, tech: "internal, sync" }',
  '  - { id: db, col: 2, row: 2, kind: db, name: Postgres, tech: orders }',
  '  - { id: q, col: 3, row: 2, kind: queue, name: fulfilment.jobs, tech: SQS }',
  '  - { id: stock, col: 1, row: 2, kind: service, name: inventory, tech: "internal, sync" }',
  'edges:',
  '  - { from: web, to: api, label: POST /orders }',
  '  - { from: api, to: stock, label: reserve }',
  '  - { from: api, to: pay, label: charge }',
  '  - { from: api, to: db }',
  '  - { from: api, to: q, label: order.confirmed }',
  '```',
  '',
  '## Service levels',
  '',
  '```slo',
  'id: svc-slo',
  'title: What we promise, and where we are',
  'items:',
  '  - { name: Order submission availability, sli: Non-5xx on POST /orders, target: "99.95%", current: "99.97%", window: 30d, budget: 0.42 }',
  '  - { name: Submission latency, sli: p95 end to end, target: < 800ms, current: 610ms, window: 30d, budget: 0.31 }',
  '  - { name: Fulfilment handoff, sli: order.confirmed published within 5s, target: "99.9%", current: "99.4%", window: 30d, budget: 0.87 }',
  '```',
  '',
  '## Dependencies',
  '',
  '```table',
  'id: svc-deps',
  'columns: [Dependency, Kind, If it is down]',
  'rows:',
  '  - ["payments", "Sync, blocking", { v: "Submission fails — this is a hard dependency", tone: neg }]',
  '  - ["inventory", "Sync, blocking", { v: "Falls back to optimistic reservation for 10 minutes", tone: warn }]',
  '  - ["Postgres", "Sync, blocking", { v: "Total outage — fail fast and page", tone: neg }]',
  '  - ["Redis", "Sync, degraded", { v: "Retries stop being idempotent; we fail closed", tone: warn }]',
  '  - ["fulfilment.jobs (SQS)", "Async", { v: "Orders confirm and queue locally; handoff catches up", tone: pos }]',
  '```',
  '',
  '## Common operations',
  '',
  '```steps',
  'id: svc-ops',
  'title: The three things people ask for',
  'items:',
  '  - title: Find one order end to end',
  '    body: The order id is in every log line and every span.',
  '    code: "kubectl logs -n orders -l app=orders-api --since=1h | grep ord_01H…"',
  '    lang: bash',
  '  - title: Replay a stuck fulfilment handoff',
  '    body: Safe to run twice — the consumer is idempotent on order id.',
  '    code: ./bin/orders replay-handoff --order ord_01H… --dry-run=false',
  '    lang: bash',
  '  - title: Roll back a bad release',
  '    code: kubectl -n orders rollout undo deploy/orders-api',
  '    lang: bash',
  '    note: Schema changes are expand-only, so a rollback never needs a database change.',
  '```',
  '',
  '```faq',
  'id: svc-faq',
  'title: Questions we answer weekly',
  'items:',
  '  - { q: Can I write to the orders table from my service?, a: "No. Order state has one owner. Subscribe to order.confirmed, or ask us for an endpoint." }',
  '  - { q: Why did an order confirm but never ship?, a: "Almost always a stuck handoff — check the fulfilment.jobs DLQ, then replay it with the command above." }',
  '  - { q: How do I test against it locally?, a: "docker compose up in the repo root brings up the API, Postgres and a fake payments service seeded with test cards." }',
  '  - { q: What is the retention on orders?, a: "Seven years, legally required. Deletion requests redact PII in place and keep the financial record." }',
  '```',
  '',
].join('\n');

const RELEASE_NOTES_TEMPLATE = [
  '```meta',
  'title: Orders API v2.4.0',
  'subtitle: Idempotency keys, partial refunds, and a faster order search.',
  'tag: Release · 2026-04-09',
  '```',
  '',
  '```callout',
  'tone: warn',
  'title: One breaking change',
  'body: "`GET /orders` no longer returns `line_items` by default. Ask for it with `?include=line_items`. The old shape is available on v2.3 until 2026-07-01."',
  '```',
  '',
  '## Highlights',
  '',
  '```stats',
  'id: rel-highlights',
  'stats:',
  '  - { value: "0", label: Duplicate charges since 2.4-rc1, delta: was 9/quarter, trend: up }',
  '  - { value: "180ms", label: Order search p95, delta: "-1.2s", trend: up }',
  '  - { value: "3", label: Endpoints deprecated, trend: flat }',
  '```',
  '',
  '## Changes',
  '',
  '```changelog',
  'id: rel-log',
  'releases:',
  '  - version: 2.4.0',
  '    date: 2026-04-09',
  '    tag: minor',
  '    items:',
  '      - { text: "Idempotency-Key on all mutating routes — retries replay the first response", type: added }',
  '      - { text: Partial refunds against a captured payment, type: added }',
  '      - { text: "Order search moves to a materialized view — p95 1.4s → 180ms", type: changed }',
  '      - { text: "GET /orders omits line_items unless requested", type: changed }',
  '      - { text: Cancelling an already-shipped order returned 500 instead of 409, type: fixed }',
  '      - { text: Signed webhook payloads now include the delivery attempt number, type: security }',
  '  - version: 2.3.2',
  '    date: 2026-03-21',
  '    tag: patch',
  '    items:',
  '      - { text: Fulfilment handoff retried forever on a poisoned message, type: fixed }',
  '```',
  '',
  '## Upgrading',
  '',
  '```steps',
  'id: rel-upgrade',
  'title: Twenty minutes, in this order',
  'items:',
  '  - title: Bump the SDK',
  '    code: npm install @acme/orders-sdk@2.4.0',
  '    lang: bash',
  '  - title: Ask for line items where you need them',
  '    body: The compiler will not catch this — grep for order list calls that read line_items.',
  '  - title: Send an idempotency key',
  '    body: One key per user action, persisted with the pending request so a retry after a cold start reuses it.',
  '  - title: Verify against staging',
  '    body: Replay yesterday\'s traffic and diff the responses before you promote.',
  '    code: ./scripts/replay --from staging --since 24h --diff',
  '    lang: bash',
  '```',
  '',
  '```code',
  'id: rel-diff',
  'kind: diff',
  'title: What the change looks like in a caller',
  'code: |',
  '  - const { orders } = await client.orders.list({ status: "open" })',
  '  + const { orders } = await client.orders.list({',
  '  +   status: "open",',
  '  +   include: ["line_items"],',
  '  + })',
  '',
  '  - await client.orders.create(payload)',
  '  + await client.orders.create(payload, { idempotencyKey: actionId })',
  '```',
  '',
  '## Deprecations',
  '',
  '```inventory',
  'id: rel-deprecations',
  'title: On the way out',
  'items:',
  '  - { name: GET /orders/search, status: deprecated, tag: removed in 3.0, note: Use GET /orders with the q parameter. }',
  '  - { name: order.updated webhook, status: deprecated, tag: removed in 3.0, note: Replaced by the typed order.status_changed event. }',
  '  - { name: X-Request-Id header, status: deprecated, tag: removed in 3.0, note: Use traceparent — we propagate W3C trace context now. }',
  '  - { name: Partial refunds, status: beta, tag: 2.4, note: Stable once the PSP reconciliation job has run a full month. }',
  '```',
  '',
].join('\n');

const TEST_PLAN_TEMPLATE = [
  '```meta',
  'title: Test plan — checkout rewrite',
  'subtitle: What we verify before the new checkout takes real traffic, and what would stop the release.',
  'tag: Test plan · Release 2026-05',
  '```',
  '',
  '```callout',
  'tone: note',
  'title: Exit criteria in one line',
  'body: "Every P0 case passes, the payment matrix is green in staging against the PSP sandbox, and a 2-hour soak at 3× peak holds p95 under 800ms."',
  '```',
  '',
  '## Scope',
  '',
  '```cvt',
  'id: tp-scope',
  'title: What this plan covers',
  'current:',
  '  label: In scope',
  '  items:',
  '    - The full submit path — cart to confirmed order',
  '    - All four payment methods, including 3DS challenge and decline paths',
  '    - Idempotent retries under packet loss',
  '    - Rollback to the old checkout behind the flag',
  'target:',
  '  label: Out of scope',
  '  items:',
  '    - Fulfilment beyond the handoff event (covered by the fulfilment suite)',
  '    - Marketing pages and the cart UI, unchanged in this release',
  '    - Load beyond 3× peak — a separate capacity exercise',
  '```',
  '',
  '## Coverage',
  '',
  '```table',
  'id: tp-matrix',
  'columns: [Case, Priority, Type, Owner]',
  'rows:',
  '  - ["Card payment, happy path", { v: "P0", tone: neg }, "e2e", "QA"]',
  '  - ["3DS challenge accepted", { v: "P0", tone: neg }, "e2e", "QA"]',
  '  - ["3DS challenge abandoned", { v: "P0", tone: neg }, "e2e", "QA"]',
  '  - ["Card declined, customer retries with another card", { v: "P0", tone: neg }, "e2e", "QA"]',
  '  - ["Retry after a dropped response charges once", { v: "P0", tone: neg }, "integration", "Payments"]',
  '  - ["Stock runs out between reserve and capture", { v: "P1", tone: warn }, "integration", "Orders"]',
  '  - ["Wallet payment (Apple Pay)", { v: "P1", tone: warn }, "e2e", "QA"]',
  '  - ["Flag off — old checkout still works", { v: "P0", tone: neg }, "smoke", "Orders"]',
  '  - ["Screen reader completes the flow", { v: "P1", tone: warn }, "manual", "Design"]',
  '```',
  '',
  '## Environments',
  '',
  '```spec',
  'id: tp-envs',
  'title: Where each layer runs',
  'rows:',
  '  - { label: Unit + integration, value: CI on every PR · PSP stubbed }',
  '  - { label: End to end, value: staging · PSP sandbox · seeded catalogue }',
  '  - { label: Soak, value: perf cluster · 3× peak for 2 hours · production-sized data }',
  '  - { label: Manual + accessibility, value: staging · Safari/VoiceOver and Chrome/NVDA }',
  '  - { label: Production, value: "canary 5% for 24h, then staged to 100%" }',
  '```',
  '',
  '## How to run it',
  '',
  '```steps',
  'id: tp-run',
  'items:',
  '  - title: The fast loop',
  '    body: Unit and integration against stubs — this is what CI gates on.',
  '    code: pnpm test --filter checkout',
  '    lang: bash',
  '  - title: End to end against staging',
  '    code: pnpm e2e --project=checkout --env=staging',
  '    lang: bash',
  '    note: Needs a PSP sandbox key in your environment; ask #team-payments.',
  '  - title: The soak',
  '    body: Two hours at 3× peak. Watch p95 and the error budget, not the total request count.',
  '    code: k6 run perf/checkout-soak.js --vus 900 --duration 2h',
  '    lang: bash',
  '```',
  '',
  '## Status',
  '',
  '```statustable',
  'id: tp-status',
  'columns: [Suite, Latest run]',
  'rows:',
  '  - { cells: [Unit + integration, "1,412 cases green on main"], status: completed }',
  '  - { cells: [Payment matrix (e2e), "18 of 20 green — two 3DS cases flaking on sandbox timeouts"], status: in progress }',
  '  - { cells: [Idempotent retry under loss, "Green — 10k retries, zero duplicate charges"], status: completed }',
  '  - { cells: [Soak at 3× peak, "Scheduled for Thursday once the payment matrix is green"], status: todo }',
  '  - { cells: [Accessibility pass, "Blocked on the final focus-order fix"], status: blocked }',
  '```',
  '',
  '## Exit criteria',
  '',
  '```list',
  'id: tp-exit',
  'style: check',
  'items:',
  '  - { lead: Every P0 case green, text: "No known P0 failure, no skipped P0", done: false }',
  '  - { lead: Zero duplicate charges, text: Across the full retry-under-loss run, done: true }',
  '  - { lead: p95 under 800ms at 3× peak, text: Held for the full two-hour soak, done: false }',
  '  - { lead: Rollback rehearsed, text: Flag flipped off in staging and the old checkout served traffic, done: true }',
  '  - { lead: Accessibility sign-off, text: Both screen-reader paths complete without a sighted assist, done: false }',
  '```',
  '',
].join('\n');

const ONBOARDING_TEMPLATE = [
  '```meta',
  'title: Onboarding — payments platform',
  'subtitle: From laptop to merged pull request in your first week.',
  'tag: Onboarding · Engineering',
  '```',
  '',
  '```callout',
  'tone: tip',
  'title: The goal for week one',
  'body: "Ship something small to production by Friday. Everything below exists to make that possible — if a step blocks you for more than 30 minutes, that is a bug in this document. Tell us and we will fix it."',
  '```',
  '',
  '## Day one',
  '',
  '```steps',
  'id: ob-setup',
  'title: Get it running locally',
  'items:',
  '  - title: Clone and install',
  '    code: "git clone git@github.com:acme/payments.git && cd payments && make bootstrap"',
  '    lang: bash',
  '    note: Bootstrap installs the toolchain versions from .tool-versions — do not install Go or Node by hand.',
  '  - title: Bring up the stack',
  '    body: Postgres, Redis, a fake PSP and the API, all in containers.',
  '    code: make up',
  '    lang: bash',
  '  - title: Prove it works',
  '    body: A seeded test card charges through the fake PSP and confirms an order.',
  '    code: make smoke',
  '    lang: bash',
  '  - title: Get your accounts',
  '    body: Open the access request template — it grants AWS read-only, Grafana, Honeycomb and PagerDuty shadow in one go.',
  '    note: Production write access comes after your first on-call shadow, not before.',
  '```',
  '',
  '## How the code is laid out',
  '',
  '```tree',
  'id: ob-layout',
  'title: The four directories that matter',
  'nodes:',
  '  - { id: root, label: payments/ }',
  '  - { id: cmd, parent: root, label: cmd/, note: "One directory per binary — api, worker, cli" }',
  '  - { id: internal, parent: root, label: internal/ }',
  '  - { id: domain, parent: internal, label: domain/, note: "Pure business rules. No SQL, no HTTP, no clock — this is where logic belongs" }',
  '  - { id: adapters, parent: internal, label: adapters/, note: "Postgres, Redis, PSP clients. Everything that talks to the outside world" }',
  '  - { id: http, parent: internal, label: http/, note: "Handlers and middleware. Thin — they translate, they do not decide" }',
  '  - { id: migrations, parent: root, label: migrations/, note: Expand-only. Never edit a migration that has run in production }',
  '  - { id: docs, parent: root, label: docs/, note: "This document, the ADRs, and the runbooks" }',
  '```',
  '',
  '## How a payment actually flows',
  '',
  '```sequence',
  'id: ob-flow',
  'title: Read this once and the codebase makes sense',
  'actors:',
  '  - { id: client, name: Storefront }',
  '  - { id: http, name: http/, sub: handler }',
  '  - { id: domain, name: domain/, sub: the rules }',
  '  - { id: psp, name: PSP, external: true }',
  'messages:',
  '  - { from: client, to: http, label: POST /payments, kind: sync }',
  '  - { from: http, to: domain, label: Charge(cmd), kind: sync, note: The handler has already validated and mapped the request. }',
  '  - { from: domain, to: psp, label: via the adapter interface, kind: sync, note: domain never imports the PSP package — it depends on an interface it owns. }',
  '  - { from: psp, to: domain, label: authorization, kind: response }',
  '  - { from: domain, to: http, label: Payment, kind: response }',
  '  - { from: http, to: client, label: 201 Created, kind: response }',
  '```',
  '',
  '## Your first tickets',
  '',
  '```kanban',
  'id: ob-first',
  'columns:',
  '  - label: Day 1-2',
  '    cards:',
  '      - { title: Fix a typo in an error message, tag: warm-up }',
  '      - { title: Add a test for an uncovered branch, tag: warm-up }',
  '  - label: Day 3-4',
  '    cards:',
  '      - { title: Add a field to an existing endpoint, tag: real }',
  '      - { title: Shadow an on-call handover, tag: ops }',
  '  - label: Week 2',
  '    cards:',
  '      - { title: Own a small feature end to end, tag: real }',
  '```',
  '',
  '## Who to ask',
  '',
  '```team',
  'id: ob-team',
  'members:',
  '  - { name: Your onboarding buddy, role: Engineer, focus: First port of call for anything, accent: teal }',
  '  - { name: Tech lead, role: Payments, focus: Architecture and review, accent: navy }',
  '  - { name: EM, role: Payments, focus: "Expectations, growth, time off", accent: purple }',
  '  - { name: "#team-payments", role: Channel, focus: Anything the above are asleep for, accent: gray }',
  '```',
  '',
  '```faq',
  'id: ob-faq',
  'title: Things nobody writes down',
  'items:',
  '  - { q: How do I get a change to production?, a: "Open a PR, get one approval, merge. It canaries at 10% for 20 minutes and promotes itself. There is no release train and no ticket to file." }',
  '  - { q: Am I allowed to break staging?, a: "Yes. That is what it is for. Production is the one that pages people." }',
  '  - { q: Where do decisions live?, a: "docs/adr/. If you are wondering why something is the way it is, the answer is usually there — and if it is not, write one." }',
  '  - { q: What if I break production?, a: "Roll back first, understand later. Nobody is in trouble for an outage; people are in trouble for hiding one. We write a blameless postmortem and move on." }',
  '  - { q: When do I join the on-call rota?, a: "After two shadow shifts, and only when you want to. Usually around week six." }',
  '```',
  '',
].join('\n');

const STATUS_UPDATE_TEMPLATE = [
  '```meta',
  'title: Payments platform — week 12',
  'subtitle: Wallets are in canary, the PSP contract slipped, and we need a decision on bank transfers.',
  'tag: Status · Steering committee',
  '```',
  '',
  '```scqa',
  'id: su-summary',
  'situation: Payments is midway through H2 — wallets, bank transfers and chargeback automation, in that order.',
  'complication: The PSP contract for bank transfers is two weeks late in legal, and that work is on the critical path for the Q4 revenue target.',
  'question: Do we hold the October date and cut scope, or move the date and keep the full scope?',
  'answer: "**Hold the date and cut scope to SEPA only.** ACH moves to Q1."',
  'because:',
  '  - SEPA is 78% of the forecast transfer volume, so most of the revenue lands on time',
  '  - ACH needs a separate compliance review we have not started, and that is the real long pole',
  '  - Cutting now keeps the wallets GA date, which is already committed to two enterprise customers',
  '```',
  '',
  '## Where we are',
  '',
  '```stats',
  'id: su-numbers',
  'stats:',
  '  - { value: "99.97%", label: Checkout availability, delta: "+0.02pp", trend: up }',
  '  - { value: "610ms", label: Checkout p95, delta: "-190ms", trend: up }',
  '  - { value: "12%", label: Wallet share in canary, delta: "+12pp", trend: up }',
  '  - { value: "2 wks", label: Bank transfers behind, delta: slipped, trend: down }',
  '```',
  '',
  '## Workstreams',
  '',
  '```statustable',
  'id: su-workstreams',
  'columns: [Workstream, Latest, Owner]',
  'statuses:',
  '  - { label: on track, color: green }',
  '  - { label: at risk, color: amber }',
  '  - { label: slipped, color: red }',
  'rows:',
  '  - { cells: [Wallets GA, "Canary at 10% for nine days — zero incidents. GA on the 22nd", Payments], status: on track }',
  '  - { cells: [Bank transfers, "PSP contract still in legal redlines; build is ready to start", Payments], status: slipped }',
  '  - { cells: [Chargeback automation, "Design complete, starts when wallets ship", Payments], status: on track }',
  '  - { cells: [Idempotency rollout, "SDKs shipping; header miss rate down to 4%", Payments], status: at risk }',
  '```',
  '',
  '## Decisions we need today',
  '',
  '```list',
  'id: su-decisions',
  'style: number',
  'items:',
  '  - { lead: Cut ACH to Q1, text: Keeps the October date for SEPA. Needs a call from Finance on the forecast impact. }',
  '  - { lead: Approve two contractors for chargebacks, text: Six-week engagement — otherwise it starts in November and misses the quarter. }',
  '  - { lead: Confirm the wallets GA comms date, text: Marketing needs ten working days of lead time. }',
  '```',
  '',
  '## Risks',
  '',
  '```risk',
  'id: su-risks',
  'items:',
  '  - { risk: PSP contract slips a further two weeks, likelihood: med, impact: high, mitigation: Second provider approached as a fallback — two weeks to integrate, owner: Finance, status: mitigating }',
  '  - { risk: Wallet canary hides a scale problem, likelihood: low, impact: high, mitigation: Load test at 10× canary volume before GA, owner: Payments, status: mitigating }',
  '  - { risk: Chargeback work starts too late for Q4, likelihood: high, impact: med, mitigation: Contractor approval today makes the date; otherwise it moves, owner: Steering, status: open }',
  '```',
  '',
  '```takeaways',
  'id: su-close',
  'items:',
  '  - text: Wallets are on track and GA on the 22nd',
  '    detail: Nine days in canary, zero incidents.',
  '  - text: Bank transfers slipped on the contract, not the build',
  '    detail: Engineering is ready to start the day it signs.',
  '  - text: Cutting ACH to Q1 keeps the October revenue',
  '  - text: Two decisions today, or chargebacks miss Q4',
  '```',
  '',
].join('\n');

/** Full-document templates, keyed by name (`avo template <name>`). */
export const DOC_TEMPLATES: Record<string, string> = {
  adr: ADR_TEMPLATE,
  'design-doc': DESIGN_DOC_TEMPLATE,
  runbook: RUNBOOK_TEMPLATE,
  roadmap: ROADMAP_TEMPLATE,
  'api-spec': API_SPEC_TEMPLATE,
  'system-design': SYSTEM_DESIGN_TEMPLATE,
  'agent-system': AGENT_SYSTEM_TEMPLATE,
  'design-system': DESIGN_SYSTEM_TEMPLATE,
  postmortem: POSTMORTEM_TEMPLATE,
  'data-model': DATA_MODEL_TEMPLATE,
  deck: DECK_TEMPLATE,
  'migration-plan': MIGRATION_PLAN_TEMPLATE,
  'threat-model': THREAT_MODEL_TEMPLATE,
  'service-overview': SERVICE_OVERVIEW_TEMPLATE,
  'release-notes': RELEASE_NOTES_TEMPLATE,
  'test-plan': TEST_PLAN_TEMPLATE,
  onboarding: ONBOARDING_TEMPLATE,
  'status-update': STATUS_UPDATE_TEMPLATE,
};

/** Display info for one document template — what a picker card shows. */
export interface DocTemplateInfo {
  /** Human display name (e.g. "ADR", "Design doc"). */
  readonly title: string;
  /** One line on when to reach for this template. */
  readonly description: string;
}

/**
 * Picker display data per template, keyed like {@link DOC_TEMPLATES} (and
 * covering exactly the same names — tested).
 */
export const DOC_TEMPLATE_INFO: Record<string, DocTemplateInfo> = {
  adr: {
    title: 'ADR',
    description: 'An architecture decision record — status, context, the decision, options, consequences.',
  },
  'design-doc': {
    title: 'Design doc',
    description: 'An RFC-style proposal — problem, goals, proposed design, alternatives, rollout.',
  },
  runbook: {
    title: 'Runbook',
    description: 'An operational how-to — prerequisites, numbered steps with commands, verification, rollback.',
  },
  roadmap: {
    title: 'Roadmap',
    description: 'A plan over time — phases on a timeline, a board of workstreams, and status tracking.',
  },
  'api-spec': {
    title: 'API spec',
    description: 'An API reference — endpoint cards with params, bodies, responses, and examples.',
  },
  'system-design': {
    title: 'System design',
    description: 'A system-design write-up — requirements, capacity math, architecture, data model, SLOs.',
  },
  'agent-system': {
    title: 'Agent system',
    description: 'An AI-agent design — the agent loop, tools, prompt anatomy, context budget, and a trace.',
  },
  'design-system': {
    title: 'Design system',
    description: 'A design-system reference — palette, type scale, do/don\'t guidance, component inventory.',
  },
  postmortem: {
    title: 'Postmortem',
    description: 'An incident review — impact, timeline, root cause, and follow-up actions.',
  },
  'data-model': {
    title: 'Data model',
    description: 'A data-model reference — the ERD, per-entity tables, and lifecycle states.',
  },
  deck: {
    title: 'Deck',
    description: 'A slide deck — cover, dividers, big numbers, charts, and a takeaways close.',
  },
  'migration-plan': {
    title: 'Migration plan',
    description: 'A phased cutover — before/after, phases, the runbook, rollback, and the risk register.',
  },
  'threat-model': {
    title: 'Threat model',
    description: 'A security review — scope, the data flow across the trust boundary, threats, and controls.',
  },
  'service-overview': {
    title: 'Service overview',
    description: 'The page you want at 3am — owner, architecture, SLOs, dependencies, and common operations.',
  },
  'release-notes': {
    title: 'Release notes',
    description: 'What shipped — highlights, the changelog, breaking changes, upgrade steps, deprecations.',
  },
  'test-plan': {
    title: 'Test plan',
    description: 'What gets verified — scope, the case matrix, environments, suite status, and exit criteria.',
  },
  onboarding: {
    title: 'Onboarding',
    description: 'A new joiner\'s first week — local setup, the code map, how a request flows, who to ask.',
  },
  'status-update': {
    title: 'Status update',
    description: 'A steering-committee update — SCQA summary, the numbers, workstreams, decisions needed.',
  },
};

/** True when `name` is a full-document template rather than a block type. */
export function isDocTemplate(name: string): boolean {
  return Object.prototype.hasOwnProperty.call(DOC_TEMPLATES, name);
}
